"""Engine-authored co-PI method bundle: SKILL.md text and the SessionStart hook (U4 §1-2)."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

from memoria_vault.product.copi_conversational_ask import (
    PRIORS_REFUSAL,
    conversational_ask_section,
)
from memoria_vault.product.copi_skill import (
    DIRECT_WRITE_REFUSAL,
    GROUNDING_MAXIM,
    SESSION_STATUS_HOOK_RELPATH,
    SKILL_RELPATH,
    SKILL_SECTION_TITLES,
    copi_bundle_files,
    render_codex_condensed_method,
    render_copi_skill,
    render_session_status_hook,
)
from memoria_vault.runtime import retrieval_pipeline
from memoria_vault.runtime.capabilities import iter_capability_manifests
from tests.helpers import copy_memoria_dirs

pytestmark = pytest.mark.contract

METHOD_OPERATION_IDS = (
    "answer-query",
    "analyze-gaps",
    "compare-and-contrast",
    "surface-tensions",
    "red-team-argument",
    "generate-questions",
    "analyze-project-argument",
)


def _flat(text: str) -> str:
    """Collapse the markdown's cosmetic line wrapping so sentence pins survive a reflow."""
    return " ".join(text.split())


def _honest_empty_skeleton() -> list[str]:
    """The count-free fragments of a real engine-rendered honest-empty sentence.

    Produced, never hand-written: `retrieval_pipeline.honest_empty` is the one
    renderer, so this list changes with the engine and a method text that
    reintroduces a fillable template is caught by the assertions below.
    """
    stages = retrieval_pipeline.PipelineStages(40)
    stages.add_ranked(0)
    stages.add_returned(0)
    rendered = retrieval_pipeline.honest_empty(
        stages.rows(), retrieval_pipeline.excluded_strata(unchecked=12)
    )
    skeleton = [part for part in re.split(r"\d+", rendered) if len(part.strip()) > 8]
    assert skeleton, f"honest-empty wording has no count-free text to look for: {rendered!r}"
    return skeleton


# --- SKILL.md method text ------------------------------------------------


def test_skill_text_contains_the_method_sections_in_order() -> None:
    text = render_copi_skill()

    assert SKILL_SECTION_TITLES == (
        "Operation vocabulary",
        "Grounding discipline",
        "Conversational ask — grounding contract",
        "Disposition etiquette",
        "Toulmin question taxonomy",
        "Argument-health reading guide",
    )
    positions = [text.index(f"\n## {title}\n") for title in SKILL_SECTION_TITLES]
    assert positions == sorted(positions)


def test_skill_text_is_a_generated_claude_skill_file() -> None:
    text = render_copi_skill()

    assert text.startswith("---\nname: memoria-copi\n")
    assert "description:" in text.split("---", 2)[1]
    assert "Generated by memoria_vault.product.copi_skill" in text


def test_skill_text_embeds_the_conversational_ask_section_verbatim() -> None:
    """Cross-section contract 7: U4-A composes U4-C's section, it never re-authors it."""
    text = render_copi_skill()

    assert conversational_ask_section() in text
    assert PRIORS_REFUSAL in text


def test_skill_text_carries_the_grounding_and_direct_write_wordings() -> None:
    text = render_copi_skill()

    assert GROUNDING_MAXIM in text
    assert DIRECT_WRITE_REFUSAL in text


def test_skill_text_names_only_operations_the_engine_actually_ships() -> None:
    """A method that names a nonexistent operation teaches an unrunnable move."""
    text = render_copi_skill()
    catalog = {
        str(manifest["frontmatter"]["operation_id"])
        for manifest in iter_capability_manifests("operation")
    }

    assert set(METHOD_OPERATION_IDS) <= catalog
    for operation_id in METHOD_OPERATION_IDS:
        assert f"`{operation_id}`" in text


def test_skill_text_teaches_the_grounds_vocabulary() -> None:
    text = render_copi_skill()

    for grounds_type in ("single-span", "multi-span", "multi-hop", "computed", "implicit"):
        assert f"`{grounds_type}`" in text
    for role in (
        "grounds-seeking",
        "warrant-challenging",
        "rebuttal-probing",
        "qualifier-testing",
    ):
        assert role in text


def test_bundle_text_carries_no_fillable_honest_empty_template() -> None:
    """2026-08-01 amendment: the engine renders honest-empty per query, never the agent."""
    skeleton = _honest_empty_skeleton()

    for rendered in (render_copi_skill(), render_codex_condensed_method()):
        text = _flat(rendered)
        assert [part for part in skeleton if part.strip() in text] == []
    assert "unknowns[0]" in _flat(render_codex_condensed_method())


def test_condensed_method_carries_the_load_bearing_wordings() -> None:
    text = render_codex_condensed_method()

    assert text.startswith("## Co-PI method (condensed)")
    assert GROUNDING_MAXIM in text
    assert "The machine proposes; the PI disposes" in text
    assert SKILL_RELPATH in text
    for operation_id in METHOD_OPERATION_IDS:
        assert f"`{operation_id}`" in text


# --- SessionStart hook ---------------------------------------------------

ENGINE_MISSING_GOLDEN = (
    "Memoria: engine missing — the Memoria CLI was not found (tried: `memoria`). "
    "Install it: `pipx install memoria`. This vault remains fully readable and "
    "editable; agent writes stay blocked until the engine exists.\n"
    "Memoria: co-PI method at .claude/skills/memoria-copi/SKILL.md — read it "
    "before answering questions about vault content.\n"
)

DOCTOR_REPORT_JSON = (
    '{"ok": false,'
    ' "credentials": ['
    '{"name": "KILOCODE_API_KEY", "class": "required-for-operation", "status": "unset"},'
    '{"name": "OPENALEX_API_KEY", "class": "enhancing", "status": "unset",'
    ' "effect_when_unset": "keyless polite-pool mode (lower rate limits)"},'
    '{"name": "GITHUB_TOKEN", "class": "enhancing", "status": "unset",'
    ' "effect_when_unset": "anonymous rate limits."},'
    '{"name": "PUBMED_API_KEY", "class": "enhancing", "status": "unset"},'
    '{"name": "NCBI_EMAIL", "class": "identity", "status": "unset"},'
    '{"name": "SEMANTIC_SCHOLAR_API_KEY", "class": "enhancing", "status": "set"},'
    '{"name": "  ", "class": "enhancing", "status": "unset"},'
    '"not-a-credential-row"'
    "]}"
)

DOCTOR_GOLDEN = (
    "Memoria: credential KILOCODE_API_KEY is unset (required-for-operation) — "
    "live-model calls refuse before the network; "
    "run `memoria secrets set KILOCODE_API_KEY`.\n"
    "Memoria: credential OPENALEX_API_KEY is unset (enhancing) — "
    "keyless polite-pool mode (lower rate limits).\n"
    "Memoria: credential GITHUB_TOKEN is unset (enhancing) — anonymous rate limits.\n"
    "Memoria: credential PUBMED_API_KEY is unset (enhancing) — degraded keyless mode.\n"
    "Memoria: co-PI method at .claude/skills/memoria-copi/SKILL.md — read it "
    "before answering questions about vault content.\n"
)

METHOD_POINTER_GOLDEN = (
    "Memoria: co-PI method at .claude/skills/memoria-copi/SKILL.md — read it "
    "before answering questions about vault content.\n"
)

DOCTOR_UNAVAILABLE_GOLDEN = (
    "Memoria: `memoria doctor` did not return usable status — run `memoria doctor` manually.\n"
) + METHOD_POINTER_GOLDEN


def _stub_memoria(bin_dir: Path, stdout_payload: str) -> None:
    """Put a `memoria` on PATH that prints one canned doctor report.

    The stub is a Python script, not a shell script: the hook's PATH holds only
    this directory, so a `/bin/sh` stub reaching for `cat` would fail to resolve
    it and every stubbed case would collapse into the doctor-unavailable branch.

    It answers only the exact argv the hook is supposed to send. A stub that
    printed its payload for any argv would let the hook drop `--json` (and get
    back human-readable text on a real machine) with every test still green.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    stub = bin_dir / "memoria"
    stub.write_text(
        f"#!{sys.executable}\n"
        "import sys\n"
        'if sys.argv[1:] == ["doctor", "--json"]:\n'
        f"    sys.stdout.write({stdout_payload!r})\n",
        encoding="utf-8",
    )
    stub.chmod(0o755)


def _run_seeded_hook(tmp_path: Path, path_dir: Path) -> str:
    hook = tmp_path / ".claude/hooks/session_status.py"
    hook.parent.mkdir(parents=True, exist_ok=True)
    hook.write_text(render_session_status_hook(), encoding="utf-8")
    proc = subprocess.run(
        [sys.executable, str(hook)],
        capture_output=True,
        cwd=tmp_path,
        env={"PATH": str(path_dir)},
        timeout=60,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr.decode("utf-8", "replace")
    return proc.stdout.decode("utf-8")


def test_bundle_enumerates_the_two_method_files() -> None:
    pairs = copi_bundle_files()

    assert [rel for rel, _ in pairs] == [SKILL_RELPATH, SESSION_STATUS_HOOK_RELPATH]
    for _, provider in pairs:
        content = provider()
        assert isinstance(content, str) and content


def test_hook_source_is_stdlib_only_and_matches_the_provider() -> None:
    text = render_session_status_hook()

    assert "import memoria_vault" not in text
    assert "from memoria_vault" not in text
    from memoria_vault.product.copi_skill import session_status

    assert text == Path(session_status.__file__).read_text(encoding="utf-8")


def test_hook_engine_missing_golden(tmp_path: Path) -> None:
    empty_bin = tmp_path / "bin"
    empty_bin.mkdir()

    assert _run_seeded_hook(tmp_path, empty_bin) == ENGINE_MISSING_GOLDEN


def test_hook_doctor_report_golden(tmp_path: Path) -> None:
    bin_dir = tmp_path / "bin"
    _stub_memoria(bin_dir, DOCTOR_REPORT_JSON)

    assert _run_seeded_hook(tmp_path, bin_dir) == DOCTOR_GOLDEN


def test_hook_degrades_on_unparsable_doctor_output(tmp_path: Path) -> None:
    bin_dir = tmp_path / "bin"
    _stub_memoria(bin_dir, "usage: memoria doctor")

    assert _run_seeded_hook(tmp_path, bin_dir) == DOCTOR_UNAVAILABLE_GOLDEN


def test_hook_degrades_on_json_that_is_not_a_report_object(tmp_path: Path) -> None:
    bin_dir = tmp_path / "bin"
    _stub_memoria(bin_dir, "[1, 2, 3]")

    assert _run_seeded_hook(tmp_path, bin_dir) == DOCTOR_UNAVAILABLE_GOLDEN


def test_hook_says_nothing_extra_when_the_report_carries_no_credentials(tmp_path: Path) -> None:
    """A report without the key is honest silence, not the unavailable line."""
    bin_dir = tmp_path / "bin"
    _stub_memoria(bin_dir, '{"ok": true}')

    assert _run_seeded_hook(tmp_path, bin_dir) == METHOD_POINTER_GOLDEN


def test_hook_renders_the_engines_real_credential_rows(tmp_path: Path, monkeypatch) -> None:
    """The row keys the hook reads are the ones `memoria doctor --json` actually emits.

    The stub-PATH goldens above prove the rendering against a hand-written
    report; this proves the report shape itself by producing it from the engine,
    so a renamed row key fails here instead of silently emptying the hook.
    """
    from memoria_vault.product.copi_skill import session_status
    from memoria_vault.runtime.secrets import CREDENTIAL_REGISTRY, credential_report

    copy_memoria_dirs(tmp_path, "config")
    for entry in CREDENTIAL_REGISTRY:
        monkeypatch.delenv(str(entry["name"]), raising=False)
    monkeypatch.delenv("KILOCODE_API_KEY", raising=False)

    rows = credential_report(tmp_path, loaded_from_file=())
    lines = session_status._credential_lines(rows)

    assert all(row["status"] == "unset" for row in rows)
    assert len(lines) == len([row for row in rows if row["class"] != "identity"])
    assert (
        "Memoria: credential KILOCODE_API_KEY is unset (required-for-operation) — "
        "live-model calls refuse before the network; "
        "run `memoria secrets set KILOCODE_API_KEY`."
    ) in lines
    assert (
        "Memoria: credential OPENALEX_API_KEY is unset (enhancing) — "
        "openalex keyless polite-pool mode (lower rate limits)."
    ) in lines
    assert not [line for line in lines if "NCBI_EMAIL" in line]
    assert session_status.DEFAULT_ENHANCING_EFFECT not in "\n".join(lines)
