import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const outputs = [
  {
    source: "src/main.ts",
    target: "main.js",
    transform: (text) =>
      [
        "// Generated by scripts/build.mjs from src/main.ts.",
        "// The source intentionally uses Obsidian-compatible CommonJS.",
        text.trimEnd(),
        "",
      ].join("\n"),
  },
  {
    source: "src/schema.js",
    target: "schema.js",
    transform: (text) =>
      [
        "// Generated by scripts/build.mjs from src/schema.js.",
        text.trimEnd(),
        "",
      ].join("\n"),
  },
];

let drift = false;
for (const output of outputs) {
  const next = output.transform(readFileSync(path.join(root, output.source), "utf8"));
  const target = path.join(root, output.target);
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {
    current = "";
  }
  if (check) {
    if (current !== next) {
      console.error(`${output.target} is not current; run npm run build`);
      drift = true;
    }
  } else {
    writeFileSync(target, next, "utf8");
  }
}

if (drift) {
  process.exit(1);
}
