#!/usr/bin/env python3
"""Validate agent guidance and regenerate its derived reference pages."""

from __future__ import annotations

import argparse
import importlib.machinery
import importlib.util
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / ".agents"
GUIDANCE_DIRS = (".agents", ".claude")
IMPACT_SOURCE = AGENTS / "system/change-impact.yaml"
IMPACT_DOC = AGENTS / "system/change-impact-map.md"
RULESET_CONTRACT = ROOT / ".github/ruleset-contract.yaml"
GENERATED = "<!-- Generated by scripts/agents_doctor.py; edit the source YAML instead. -->"
REQUIRED_FILES = (
    "README.md",
    "playbooks/code-review.md",
    "playbooks/docs-review.md",
    "playbooks/security-review.md",
    "playbooks/verify-change.md",
    "system/change-impact.yaml",
    "system/source-of-truth-map.md",
    "system/test-selection.md",
)


def _render_impact(data: dict) -> str:
    lines = [
        GENERATED,
        "# Change-impact map",
        "",
        "This map answers: “When I change this, what else must I inspect?” It is a",
        "review frontier, not permission to edit every listed file.",
        "",
        "| Change area | Changed paths | Inspect together | Primary checks |",
        "|---|---|---|---|",
    ]
    for row in data["areas"]:
        paths = "<br>".join(f"`{item}`" for item in row["paths"])
        inspect = "<br>".join(row["inspect"])
        checks = "<br>".join(f"`{item}`" for item in row["checks"])
        lines.append(f"| {row['area']} | {paths} | {inspect} | {checks} |")
    lines.extend(
        [
            "",
            "## How to use the map",
            "",
            "1. Start from the changed row.",
            "2. Inspect each named contract for drift.",
            "3. Edit only consumers that genuinely need to change.",
            "4. Run focused checks from the row.",
            "5. Use [test selection](test-selection.md) to decide whether the full gate is required.",
            "",
        ]
    )
    return "\n".join(lines)


def _local_link_errors() -> list[str]:
    errors = []
    link_re = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    roots = [ROOT / name for name in GUIDANCE_DIRS if (ROOT / name).is_dir()]
    paths = [p for root in roots for p in root.rglob("*.md")]
    if (ROOT / "AGENTS.md").is_file():
        paths.append(ROOT / "AGENTS.md")
    for path in sorted(paths):
        for target in link_re.findall(path.read_text(encoding="utf-8")):
            target = target.split("#", 1)[0]
            if not target or "://" in target or target.startswith("#"):
                continue
            if not (path.parent / target).resolve().exists():
                errors.append(f"{path.relative_to(ROOT)}: broken link {target}")
    return errors


def _skill_errors() -> list[str]:
    errors = []
    skill_roots = [
        ROOT / ".agents" / "skills",
        ROOT / ".claude" / "skills",
    ]
    for path in sorted(p for root in skill_roots if root.is_dir() for p in root.glob("*/SKILL.md")):
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            errors.append(f"{path.relative_to(ROOT)}: missing YAML frontmatter")
            continue
        _, frontmatter, _ = text.split("---", 2)
        data = yaml.safe_load(frontmatter) or {}
        for key in ("name", "description"):
            if not data.get(key):
                errors.append(f"{path.relative_to(ROOT)}: missing {key}")
    return errors


def _required_ci_checks_from_agents(text: str) -> list[str]:
    lines = iter(text.splitlines())
    for line in lines:
        if line == "## Required CI checks":
            break
    else:
        return []

    checks = []
    in_table = False
    for line in lines:
        if line == "| Check | Validates |":
            in_table = True
            continue
        if in_table and line == "|---|---|":
            continue
        if in_table and (found := re.match(r"^\| `([^`]+)` \|", line)):
            checks.append(found.group(1))
            continue
        if in_table:
            break
    return checks


def _required_ci_errors() -> list[str]:
    expected = (yaml.safe_load(RULESET_CONTRACT.read_text(encoding="utf-8")) or {}).get(
        "required_checks"
    )
    actual = _required_ci_checks_from_agents((ROOT / "AGENTS.md").read_text(encoding="utf-8"))
    if actual != expected:
        return [
            "AGENTS.md Required CI checks drift from .github/ruleset-contract.yaml: "
            f"{actual} != {expected}"
        ]
    return []


def _load_python_file(module_name: str, path: Path):
    loader = importlib.machinery.SourceFileLoader(module_name, str(path))
    spec = importlib.util.spec_from_loader(module_name, loader)
    if spec is None:
        raise ImportError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


def _code_spans(text: str) -> list[str]:
    return re.findall(r"`([^`]+)`", text)


def _code_spans_after_label(text: str, label: str) -> set[str]:
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.startswith(label):
            block = [line]
            for continuation in lines[index + 1 :]:
                if not continuation.strip() or re.match(r"^[A-Z][A-Za-z -]+:", continuation):
                    break
                block.append(continuation)
            return set(_code_spans("\n".join(block)))
    return set()


def _pr_policy_errors(text: str | None = None, policy=None) -> list[str]:
    text = text if text is not None else (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    policy = policy or _load_python_file("memoria_pr_policy", ROOT / ".github/scripts/pr_policy.py")
    errors = []

    trusted = _code_spans_after_label(text, "Trusted authors:")
    expected_trusted = set(policy.TRUSTED_AUTHORS)
    if trusted != expected_trusted:
        errors.append(
            f"AGENTS.md trusted authors drift from pr_policy.py: {trusted} != {expected_trusted}"
        )

    sensitive = _code_spans_after_label(text, "Sensitive paths:")
    expected_sensitive = set(policy.SENSITIVE_PREFIXES) | set(policy.SENSITIVE_PATHS)
    if sensitive != expected_sensitive:
        errors.append(
            "AGENTS.md sensitive paths drift from pr_policy.py: "
            f"{sensitive} != {expected_sensitive}"
        )

    auto_row = _table_row(text, "auto_approve")
    auto_values = set(_code_spans(auto_row))
    for value in (*policy.SAFE_PROSE_PREFIXES, *policy.SAFE_SUFFIXES):
        if value not in auto_values:
            errors.append(f"AGENTS.md auto_approve row omits pr_policy.py value: {value}")

    block_row = _table_row(text, "block")
    block_values = set(_code_spans(block_row))
    for value in policy.MAIN_EXCLUDED_PREFIXES:
        if value not in block_values:
            errors.append(f"AGENTS.md block row omits pr_policy.py value: {value}")

    return errors


def _table_row(text: str, key: str) -> str:
    prefix = f"| `{key}` |"
    return next((line for line in text.splitlines() if line.startswith(prefix)), "")


def _expand_braces(pattern: str) -> list[str]:
    match = re.search(r"\{([^{}]+)\}", pattern)
    if not match:
        return [pattern]
    before, after = pattern[: match.start()], pattern[match.end() :]
    expanded = []
    for option in match.group(1).split(","):
        expanded.extend(_expand_braces(f"{before}{option}{after}"))
    return expanded


ROOT_PATHS = {
    "AGENTS.md",
    "CONTRIBUTING.md",
    "package.json",
    "pyproject.toml",
    "requirements-dev.txt",
}
PATH_PREFIXES = (".agents/", ".github/", "docs/", "scripts/", "src/", "tests/", "vault-template/")


def _source_map_path_errors(text: str | None = None, root: Path | None = None) -> list[str]:
    root = root or ROOT
    text = (
        text
        if text is not None
        else (AGENTS / "system/source-of-truth-map.md").read_text(encoding="utf-8")
    )
    errors = []
    for span in _code_spans(text):
        if "<" in span or (span not in ROOT_PATHS and not span.startswith(PATH_PREFIXES)):
            continue
        for expanded in _expand_braces(span):
            matches = list(root.glob(expanded)) if any(ch in expanded for ch in "*?[]") else []
            if matches:
                continue
            candidate = root / expanded
            if expanded.endswith("/"):
                ok = candidate.is_dir()
            else:
                ok = candidate.exists()
            if not ok:
                errors.append(f".agents/system/source-of-truth-map.md: missing path `{span}`")
                break
    return errors


def _verify_change_errors(text: str | None = None, verify_module=None) -> list[str]:
    text = (
        text
        if text is not None
        else (AGENTS / "playbooks/verify-change.md").read_text(encoding="utf-8")
    )
    verify_module = verify_module or _load_python_file(
        "memoria_verify_script", ROOT / "scripts/verify"
    )
    errors = []

    actual_gates = _verify_gate_rows(text)
    expected_gates = list(verify_module.GATE_COMMANDS)
    if actual_gates != expected_gates:
        errors.append(
            f"verify-change gate rows drift from scripts/verify: {actual_gates} != {expected_gates}"
        )

    for mode in verify_module.MODES:
        if f"`scripts/verify {mode}`" not in text:
            errors.append(f"verify-change evidence ladder omits scripts/verify mode: {mode}")
    return errors


def _verify_gate_rows(text: str) -> list[str]:
    rows = []
    in_table = False
    for line in text.splitlines():
        if line == "| Gate | Proves | Use when |":
            in_table = True
            continue
        if in_table and line == "|---|---|---|":
            continue
        if in_table and line.startswith("| "):
            cells = [cell.strip() for cell in line.strip("|").split("|")]
            rows.append(cells[0].lower())
            continue
        if in_table:
            break
    return rows


def _enforcement_mechanisms() -> set[str]:
    mechanisms = set()
    precommit = yaml.safe_load((ROOT / ".pre-commit-config.yaml").read_text(encoding="utf-8")) or {}
    for repo in precommit.get("repos", []):
        for hook in repo.get("hooks", []):
            if hook_id := hook.get("id"):
                mechanisms.add(hook_id)
    contract = yaml.safe_load(RULESET_CONTRACT.read_text(encoding="utf-8")) or {}
    mechanisms.update(contract.get("required_checks", []))
    for base in (ROOT / "scripts", ROOT / ".github/scripts"):
        if base.is_dir():
            mechanisms.update(
                path.relative_to(ROOT).as_posix() for path in base.rglob("*") if path.is_file()
            )
    return mechanisms


def _agent_tag_errors(text: str | None = None) -> list[str]:
    text = text if text is not None else (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    mechanisms = _enforcement_mechanisms()
    errors = []
    for raw in re.findall(r"\*\(enforced: (.*?)\)\*", text):
        if "<" in raw:
            continue
        for mechanism in (item.strip() for item in raw.split(",")):
            if mechanism not in mechanisms:
                errors.append(f"AGENTS.md enforcement tag names missing mechanism: {mechanism}")
    for raw in re.findall(r"\*\(enforced-by-structure: (.*?)\)\*", text):
        if "<" in raw:
            continue
        if not raw.strip():
            errors.append("AGENTS.md structural enforcement tag must name a concrete invariant")
    return errors


def generated_files() -> dict[Path, str]:
    data = yaml.safe_load(IMPACT_SOURCE.read_text(encoding="utf-8")) or {}
    if data.get("version") != 1 or not data.get("areas"):
        raise ValueError("change-impact.yaml must contain version: 1 and non-empty areas")
    return {
        IMPACT_DOC: _render_impact(data),
    }


def _impact_errors(data: dict) -> list[str]:
    errors = []
    reference_re = re.compile(r"(?:tests|scripts|src)/[A-Za-z0-9_./*-]+")
    for row in data["areas"]:
        for pattern in row["paths"]:
            prefix = re.split(r"[*?[]", pattern, maxsplit=1)[0].rstrip("/")
            candidate = ROOT / prefix
            if prefix and not candidate.exists():
                errors.append(f"change-impact.yaml: missing path prefix {prefix}")
        for command in row["checks"]:
            for reference in reference_re.findall(command):
                if "*" not in reference and not (ROOT / reference).exists():
                    errors.append(f"change-impact.yaml: command references missing {reference}")
    return errors


def check(write: bool = False) -> list[str]:
    errors = _local_link_errors() + _skill_errors()
    for relative in REQUIRED_FILES:
        if not (AGENTS / relative).is_file():
            errors.append(f".agents/{relative}: required guidance file is missing")
    try:
        agents_text = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
        errors.extend(_required_ci_errors())
        errors.extend(_pr_policy_errors(agents_text))
        errors.extend(_source_map_path_errors())
        errors.extend(_verify_change_errors())
        errors.extend(_agent_tag_errors(agents_text))
        data = yaml.safe_load(IMPACT_SOURCE.read_text(encoding="utf-8")) or {}
        errors.extend(_impact_errors(data))
        rendered = generated_files()
    except (OSError, ValueError, yaml.YAMLError) as exc:
        return [*errors, str(exc)]
    for path, expected in rendered.items():
        if write:
            path.write_text(expected, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            errors.append(f"{path.relative_to(ROOT)}: stale; run scripts/agents_doctor.py --write")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="regenerate derived references")
    args = parser.parse_args()
    errors = check(args.write)
    if errors:
        print("\n".join(f"ERROR: {error}" for error in errors), file=sys.stderr)
        return 1
    print("agents-doctor: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
