#!/usr/bin/env python3
"""Generate schema-backed reference tables."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "src/.memoria/schemas"
TYPES = SCHEMAS / "types"
START = "<!-- REFERENCE:START -->"
END = "<!-- REFERENCE:END -->"
GENERATED = "<!-- Generated by scripts/gen_reference_refs.py; edit schema sources instead. -->"
CATEGORY_ORDER = ("catalog", "projects", "notes", "inbox", "system", "spaces")
CATEGORY_LABELS = {
    "catalog": "Catalog entities",
    "projects": "Projects",
    "notes": "Notes",
    "inbox": "Inbox cards",
    "system": "System types",
    "spaces": "Navigation surfaces",
}
DOCS = (
    "docs/reference/document-types.md",
    "docs/reference/frontmatter.md",
    "docs/reference/inbox-card-fields.md",
    "docs/reference/configuration.md",
    "docs/reference/calibration.md",
)


def load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def type_schemas() -> list[dict[str, Any]]:
    rows = [load_yaml(path) for path in sorted(TYPES.glob("*.yaml"))]
    return sorted(rows, key=lambda row: (CATEGORY_ORDER.index(row["category"]), row["type"]))


def folders() -> dict[str, Any]:
    return load_yaml(SCHEMAS / "folders.yaml")


def calibration() -> dict[str, Any]:
    return load_yaml(SCHEMAS / "calibration.yaml")


def cell(value: Any) -> str:
    if value is None:
        return "`null`"
    if value == [] or value == {}:
        return "-"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (int, float)):
        return f"`{value}`"
    if isinstance(value, list):
        return " · ".join(f"`{item}`" for item in value) or "-"
    escaped = str(value).replace("|", "\\|")
    return f"`{escaped}`"


def field_names(fields: Any) -> str:
    return cell(list((fields or {}).keys()))


def lifecycle(schema: dict[str, Any]) -> str:
    return cell((schema.get("enums") or {}).get("lifecycle") or [])


def enum_values(schema: dict[str, Any], kind: str) -> str:
    if not kind.startswith("enum:"):
        return "-"
    return cell((schema.get("enums") or {}).get(kind.split(":", 1)[1]) or [])


def generated_block(lines: list[str]) -> str:
    return "\n".join([START, GENERATED, "", *lines, "", END, ""])


def render_document_types() -> str:
    all_types = type_schemas()
    home_map = folders().get("homes") or {}
    by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for schema in all_types:
        by_category[schema["category"]].append(schema)

    counts = ", ".join(
        f"{CATEGORY_LABELS[category]}: {len(by_category[category])}"
        for category in CATEGORY_ORDER
        if by_category[category]
    )
    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}` and `{(SCHEMAS / 'folders.yaml').relative_to(ROOT)}`.",
        f"Total types: **{len(all_types)}** ({counts}).",
        "",
    ]
    for category in CATEGORY_ORDER:
        rows = by_category.get(category)
        if not rows:
            continue
        lines.extend(
            [
                f"## {CATEGORY_LABELS[category]} ({len(rows)})",
                "",
                "| Type | Folder | Gated | Initial lifecycle | Lifecycle subset | Required fields | Required-any | Optional fields |",
                "| --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for schema in rows:
            doc_type = schema["type"]
            lines.append(
                "| "
                + " | ".join(
                    [
                        cell(doc_type),
                        cell(home_map.get(doc_type)),
                        cell(schema.get("gated", False)),
                        cell(schema.get("initial_lifecycle")),
                        lifecycle(schema),
                        field_names(schema.get("required")),
                        cell(schema.get("required_any") or []),
                        field_names(schema.get("optional")),
                    ]
                )
                + " |"
            )
        lines.append("")
    return generated_block(lines)


def render_frontmatter() -> str:
    schemas = type_schemas()
    lifecycle_groups: dict[str, list[str]] = defaultdict(list)
    for schema in schemas:
        lifecycle_groups[lifecycle(schema)].append(schema["type"])

    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}`.",
        "",
        "## Lifecycle subsets",
        "",
        "| Lifecycle subset | Types |",
        "| --- | --- |",
    ]
    for subset, names in sorted(lifecycle_groups.items(), key=lambda item: item[0]):
        lines.append(f"| {subset} | {cell(names)} |")

    lines.extend(
        [
            "",
            "## Enum values",
            "",
            "| Type | Enum | Values |",
            "| --- | --- | --- |",
        ]
    )
    for schema in schemas:
        for enum_name, values in sorted((schema.get("enums") or {}).items()):
            lines.append(f"| {cell(schema['type'])} | {cell(enum_name)} | {cell(values)} |")

    lines.extend(
        [
            "",
            "## Per-type fields",
            "",
            "| Type | Required | Required-any | Optional |",
            "| --- | --- | --- | --- |",
        ]
    )
    for schema in schemas:
        lines.append(
            f"| {cell(schema['type'])} | {field_names(schema.get('required'))} | "
            f"{cell(schema.get('required_any') or [])} | {field_names(schema.get('optional'))} |"
        )
    return generated_block(lines)


def render_inbox_cards() -> str:
    schemas = [schema for schema in type_schemas() if schema["category"] == "inbox"]
    lines = [
        f"Generated from Inbox schemas in `{TYPES.relative_to(ROOT)}`.",
        "",
    ]
    for schema in schemas:
        lines.extend(
            [
                f"## `{schema['type']}`",
                "",
                f"- Initial lifecycle: {cell(schema.get('initial_lifecycle'))}",
                f"- Lifecycle values: {lifecycle(schema)}",
                f"- Required-any: {cell(schema.get('required_any') or [])}",
                "",
                "| Field | Kind | Requirement | Enum values |",
                "| --- | --- | --- | --- |",
            ]
        )
        for requirement in ("required", "optional"):
            for name, kind in (schema.get(requirement) or {}).items():
                lines.append(
                    f"| {cell(name)} | {cell(kind)} | {requirement} | {enum_values(schema, kind)} |"
                )
        lines.append("")
    return generated_block(lines)


def flatten(prefix: str, value: Any) -> list[tuple[str, Any]]:
    if isinstance(value, dict):
        rows: list[tuple[str, Any]] = []
        for key, nested in value.items():
            rows.extend(flatten(f"{prefix}.{key}" if prefix else str(key), nested))
        return rows
    return [(prefix, value)]


def render_configuration() -> str:
    layout = folders()
    home_map = layout.get("homes") or {}
    lines = [
        f"Generated from `{(SCHEMAS / 'folders.yaml').relative_to(ROOT)}`.",
        "",
        "## Folder controls",
        "",
        "| Setting | Value |",
        "| --- | --- |",
        f"| Categories | {cell(layout.get('categories') or [])} |",
        f"| Gated prefixes | {cell(layout.get('gated_prefixes') or [])} |",
        f"| Transient prefixes | {cell(layout.get('transient_prefixes') or [])} |",
        f"| Skeleton entries | {cell(len(layout.get('skeleton') or []))} |",
        "",
        "## Type homes",
        "",
        "| Type | Folder |",
        "| --- | --- |",
    ]
    for doc_type, folder in sorted(home_map.items()):
        lines.append(f"| {cell(doc_type)} | {cell(folder)} |")

    lines.extend(
        [
            "",
            "## Calibration blocks",
            "",
            "| Block | Keys |",
            "| --- | --- |",
        ]
    )
    for key, value in calibration().items():
        keys = sorted(value.keys()) if isinstance(value, dict) else []
        lines.append(f"| {cell(key)} | {cell(keys)} |")
    return generated_block(lines)


def render_calibration() -> str:
    lines = [
        f"Generated from `{(SCHEMAS / 'calibration.yaml').relative_to(ROOT)}`.",
        "",
        "| Path | Value |",
        "| --- | --- |",
    ]
    for path, value in flatten("", calibration()):
        lines.append(f"| {cell(path)} | {cell(value)} |")
    return generated_block(lines)


RENDERERS = {
    "docs/reference/document-types.md": render_document_types,
    "docs/reference/frontmatter.md": render_frontmatter,
    "docs/reference/inbox-card-fields.md": render_inbox_cards,
    "docs/reference/configuration.md": render_configuration,
    "docs/reference/calibration.md": render_calibration,
}


def update(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ValueError(f"{path}: missing generated block markers")
    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    return before.rstrip() + "\n\n" + block.rstrip() + "\n\n" + after.lstrip("\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for relative in DOCS:
        path = ROOT / relative
        expected = update(path, RENDERERS[relative]())
        current = path.read_text(encoding="utf-8")
        if args.write:
            path.write_text(expected, encoding="utf-8")
        elif current != expected:
            stale.append(relative)

    if args.check and stale:
        raise SystemExit(
            "schema-backed references are stale; run scripts/gen_reference_refs.py --write: "
            + ", ".join(stale)
        )
    print("gen-reference-refs: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
