#!/usr/bin/env python3
"""Generate schema-backed reference pages and tables."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "src/.memoria/schemas"
TYPES = SCHEMAS / "types"
START = "<!-- REFERENCE:START -->"
END = "<!-- REFERENCE:END -->"
GENERATED = "<!-- Generated by scripts/gen_reference_refs.py; edit schema sources instead. -->"
GENERATED_PAGE = (
    "<!-- Generated by scripts/gen_reference_refs.py; edit schema sources or generator text "
    "instead. -->"
)
CATEGORY_ORDER = ("catalog", "projects", "notes", "inbox", "system", "spaces")
CATEGORY_LABELS = {
    "catalog": "Catalog entities",
    "projects": "Projects",
    "notes": "Notes",
    "inbox": "Inbox cards",
    "system": "System types",
    "spaces": "Navigation surfaces",
}
DOCS = (
    "docs/reference/document-types.md",
    "docs/reference/frontmatter.md",
    "docs/reference/inbox-card-fields.md",
    "docs/reference/configuration.md",
    "docs/reference/calibration.md",
)


def load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def type_schemas() -> list[dict[str, Any]]:
    rows = [load_yaml(path) for path in sorted(TYPES.glob("*.yaml"))]
    return sorted(rows, key=lambda row: (CATEGORY_ORDER.index(row["category"]), row["type"]))


def folders() -> dict[str, Any]:
    return load_yaml(SCHEMAS / "folders.yaml")


def calibration() -> dict[str, Any]:
    return load_yaml(SCHEMAS / "calibration.yaml")


def cell(value: Any) -> str:
    if value is None:
        return "`null`"
    if value == [] or value == {}:
        return "-"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (int, float)):
        return f"`{value}`"
    if isinstance(value, list):
        return " · ".join(f"`{item}`" for item in value) or "-"
    escaped = str(value).replace("|", "\\|")
    return f"`{escaped}`"


def field_names(fields: Any) -> str:
    return cell(list((fields or {}).keys()))


def lifecycle(schema: dict[str, Any]) -> str:
    return cell((schema.get("enums") or {}).get("lifecycle") or [])


def enum_values(schema: dict[str, Any], kind: str) -> str:
    if not kind.startswith("enum:"):
        return "-"
    return cell((schema.get("enums") or {}).get(kind.split(":", 1)[1]) or [])


def generated_block(lines: list[str]) -> str:
    return "\n".join([START, GENERATED, "", *lines, "", END, ""])


def generated_page(frontmatter: str, body: str) -> str:
    return frontmatter.strip() + "\n\n" + GENERATED_PAGE + "\n\n" + body.strip() + "\n"


def render_document_types() -> str:
    all_types = type_schemas()
    home_map = folders().get("homes") or {}
    by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for schema in all_types:
        by_category[schema["category"]].append(schema)

    counts = ", ".join(
        f"{CATEGORY_LABELS[category]}: {len(by_category[category])}"
        for category in CATEGORY_ORDER
        if by_category[category]
    )
    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}` and `{(SCHEMAS / 'folders.yaml').relative_to(ROOT)}`.",
        f"Total types: **{len(all_types)}** ({counts}).",
        "",
    ]
    for category in CATEGORY_ORDER:
        rows = by_category.get(category)
        if not rows:
            continue
        lines.extend(
            [
                f"## {CATEGORY_LABELS[category]} ({len(rows)})",
                "",
                "| Type | Folder | Gated | Initial lifecycle | Lifecycle subset | Required fields | Required-any | Optional fields |",
                "| --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for schema in rows:
            doc_type = schema["type"]
            lines.append(
                "| "
                + " | ".join(
                    [
                        cell(doc_type),
                        cell(home_map.get(doc_type)),
                        cell(schema.get("gated", False)),
                        cell(schema.get("initial_lifecycle")),
                        lifecycle(schema),
                        field_names(schema.get("required")),
                        cell(schema.get("required_any") or []),
                        field_names(schema.get("optional")),
                    ]
                )
                + " |"
            )
        lines.append("")
    return generated_block(lines)


def render_document_types_page() -> str:
    return generated_page(
        """---
title: Document types
parent: Vault data model
grand_parent: Reference
---""",
        f"""# Document types

The document-type schemas are authoritative: every type is defined by one YAML
file under `src/.memoria/schemas/types`, and the type-to-folder map lives in
`src/.memoria/schemas/folders.yaml` ([ADR-47](../adr/47-type-first-category-folders.md)).
This generated page is the lookup view for folder homes, lifecycle subsets, and
field presence. For field semantics, see [Frontmatter fields](frontmatter.md).

Regenerate with `python scripts/gen_reference_refs.py --write`; edit the schema
sources, not this page.

{render_document_types().rstrip()}

## Related

- Field kinds, lifecycle values, enums, and per-type field inventory:
  [Frontmatter fields](frontmatter.md)
- Inbox card contracts: [Inbox card fields](inbox-card-fields.md)
- The folder tree the homes map into: [On-disk layout](on-disk-layout.md)
- What enforces the schemas: [Linter: detectors and auto-fix](linter.md) and
  [Policy MCP](policy-mcp.md)
""",
    )


def render_frontmatter() -> str:
    schemas = type_schemas()
    lifecycle_groups: dict[str, list[str]] = defaultdict(list)
    for schema in schemas:
        lifecycle_groups[lifecycle(schema)].append(schema["type"])

    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}`.",
        "",
        "## Lifecycle subsets",
        "",
        "| Lifecycle subset | Types |",
        "| --- | --- |",
    ]
    for subset, names in sorted(lifecycle_groups.items(), key=lambda item: item[0]):
        lines.append(f"| {subset} | {cell(names)} |")

    lines.extend(
        [
            "",
            "## Enum values",
            "",
            "| Type | Enum | Values |",
            "| --- | --- | --- |",
        ]
    )
    for schema in schemas:
        for enum_name, values in sorted((schema.get("enums") or {}).items()):
            lines.append(f"| {cell(schema['type'])} | {cell(enum_name)} | {cell(values)} |")

    lines.extend(
        [
            "",
            "## Per-type fields",
            "",
            "| Type | Required | Required-any | Optional |",
            "| --- | --- | --- | --- |",
        ]
    )
    for schema in schemas:
        lines.append(
            f"| {cell(schema['type'])} | {field_names(schema.get('required'))} | "
            f"{cell(schema.get('required_any') or [])} | {field_names(schema.get('optional'))} |"
        )
    return generated_block(lines)


def render_frontmatter_page() -> str:
    return generated_page(
        """---
title: Frontmatter fields
parent: Vault data model
grand_parent: Reference
---""",
        f"""# Frontmatter fields

The frontmatter contract for every typed document. **The single source is
`.memoria/schemas/`**: per-document-type field schemas in
`src/.memoria/schemas/types`, the type-to-folder map in
`src/.memoria/schemas/folders.yaml`, and calibrated thresholds in
`src/.memoria/schemas/calibration.yaml`. The shared loader/validator is
`src/.memoria/operations/lib/schema.py`; the Linter, pre-commit hook, and
installer-skeleton tests all read it. This generated page explains the grammar
and universal fields; the per-type tables live in [Document types](document-types.md).

Regenerate with `python scripts/gen_reference_refs.py --write`; edit schema
sources or this generator, not this page.

## The field-kind grammar

Each type schema declares `required:` and `optional:` maps of `field: kind`,
plus an `enums:` block and optionally `required_any:`. The kinds:

| Kind | Accepts |
| --- | --- |
| `str` | a string |
| `int` | an integer (not a bool) |
| `bool` | a boolean |
| `date` | a YAML date or an ISO-8601 date string |
| `list` | a YAML sequence |
| `map` | a YAML mapping |
| `literal:<value>` | exactly that value; for example, `type: literal:claim` |
| `enum:<name>` | one of the values the schema's `enums.<name>` lists |

Unknown extra fields are **allowed**. A schema example (`types/claim.yaml`):

```yaml
type: claim
category: notes
gated: true
enums:
  lifecycle: [current, retracted, archived]
  maturity: [seedling, budding, evergreen]
required:
  type: literal:claim
  lifecycle: enum:lifecycle
  title: str
  maturity: enum:maturity
  sources: list
optional:
  schema_version: int
  links: map
  topics: list
  superseded_by: str
  created: date
```

{render_frontmatter().rstrip()}

## Creation metadata

Human capture forms are declared beside the validating fields when a type has an
Obsidian Modal Forms entry. The `creation.form` block owns the form name, title,
field order, labels, descriptions, required-at-entry flags, and input source
(`enum`, fixed values, note picker, or vocabulary). `scripts/gen-forms.py`
projects that metadata into the committed Modal Forms `data.json`; it does not
change the validator grammar above.

Fields such as `summary` or `claim` are creation inputs, not necessarily
frontmatter fields. The QuickAdd writer maps them into the note body or into
structured frontmatter.

## Display order and grouping

The schema validates field presence and kind; display order is a shipped-vault
convention. Templates and deterministic emitters put fields in this order:

1. Human identity: `title` or `name`.
2. Schema identity and PI-facing state: `type`, then `lifecycle`.
3. Type-specific state: `maturity`, `certainty`, `agent_recommendation`,
   `loudness`, `origin`, or `ingest_status`.
4. Primary references: `citekey`, `entity`, `target`, `task_id`, `url`, `doi`.
5. Classification and relations: `research_area`, `methodology`, `topics`,
   `sources`, `links`, `relationships`.
6. Provenance and housekeeping: owned namespaces such as `_enrichment` /
   `_proposed_classification`, labels such as `sample`, timestamps, and version
   fields.

Obsidian does not have a global property-order schema file, so the shipped
templates, emitters, and Bases carry this convention directly.

## `lifecycle` — the one chain

Every typed document carries `lifecycle`, drawn from the **universal chain**
([ADR-50](../adr/50-universal-lifecycle-and-maturity.md)):

```text
proposed → provisional → current → retracted → archived
```

Each type's schema declares the subset it uses. `proposed` always means
_awaiting the PI_. `retracted` is a state, not a deletion; supersession keeps the
lineage (`superseded_by`). The board's `status` enum is a separate hidden
execution mechanic (see [Kanban board reference](kanban-board.md)).

## `maturity` — a claim property, never a gate

Claims only: `seedling → budding → evergreen`. It describes how settled a claim
is; nothing in the system blocks on it.

## `links:` vs `relationships`

Notes (`source`, `claim`, `hub`) carry the authored `links:` map; catalog
entities carry the given `relationships` map. The authored-vs-given distinction
is owned by [Wikilink and link conventions](wikilink-and-link-conventions.md).

Project-gate argument edges may carry an optional `warrant` attribute on a
`supports` relation when the author wants to state the grounds-to-claim inference
explicitly ([ADR-79](../adr/79-argument-graph-and-warrant.md)).

## Project-gate fields

`project` and `thesis` notes add the Project gate's authored state and operation
cache ([ADR-77](../adr/77-project-gate.md), [ADR-78](../adr/78-thesis-note-type.md)).
The generated field inventory above owns the exact current field list and enum
values.

Source notes also carry optional `evidence_level`, a CEBM-style enum
(`cebm-1` … `cebm-5`, `ungraded`).

## The honesty-card fields

Inbox cards split into proposals (`candidate`, `gap`), verification cards
(`flag`, `alert`), and work prompts (`work-prompt`)
([ADR-51](../adr/51-inbox-category-and-honesty-card.md)). Their field-level
contract lives in [Inbox card fields](inbox-card-fields.md).

## Batch worklist fields

Worklist rows are `worklist-item` notes under `system/worklists/`. Their
`lifecycle` says whether the row is still active in the vault; their separate
`decision` field is the PI's batch-screening choice: `proposed`, `include`,
`exclude`, `maybe`, or `archived`. The emitter raises one aggregate
`work-prompt` for the batch, never one card per row.

## Other universal fields

| Field | Kind | Notes |
| --- | --- | --- |
| `type` | `literal:` | Pins the note to its schema. Set at creation; never changed. |
| `title` / `name` | `str` | Notes and cards use `title`; catalog entities use `name`. |
| `created` | `date` | Optional everywhere. |
| `sample` | `bool` | Optional label for bundled tutorial notes. |
| `research_area`, `methodology`, `topics` | `list` | Controlled-vocabulary classification; values live in [Vocabulary](vocabulary.md). |
| `ingest_status` | `enum` | Paper ingest floor/progress: `tier0`, `enriched`, `complete`, or `needs-human`. |

## Enforcement

| Where | What |
| --- | --- |
| Pre-commit hook | Every staged `.md` note must pass its type schema. |
| Daily Linter cron | The `schema-check` and `frontmatter-link` detectors monitor between commits. |
| Exemptions | Most `system/` infrastructure and vault-root navigation pages are untyped and exempt. |

## Related

- The per-document-type field tables: [Document types](document-types.md)
- The controlled classification values: [Vocabulary](vocabulary.md)
- What validates this contract: [Linter: detectors and auto-fix](linter.md)
- Where the schema files live: [On-disk layout](on-disk-layout.md)
""",
    )


def render_inbox_cards() -> str:
    schemas = [schema for schema in type_schemas() if schema["category"] == "inbox"]
    lines = [
        f"Generated from Inbox schemas in `{TYPES.relative_to(ROOT)}`.",
        "",
    ]
    for schema in schemas:
        lines.extend(
            [
                f"## `{schema['type']}`",
                "",
                f"- Initial lifecycle: {cell(schema.get('initial_lifecycle'))}",
                f"- Lifecycle values: {lifecycle(schema)}",
                f"- Required-any: {cell(schema.get('required_any') or [])}",
                "",
                "| Field | Kind | Requirement | Enum values |",
                "| --- | --- | --- | --- |",
            ]
        )
        for requirement in ("required", "optional"):
            for name, kind in (schema.get(requirement) or {}).items():
                lines.append(
                    f"| {cell(name)} | {cell(kind)} | {requirement} | {enum_values(schema, kind)} |"
                )
        lines.append("")
    return generated_block(lines)


def render_inbox_cards_page() -> str:
    return generated_page(
        """---
title: Inbox card fields
parent: Vault data model
grand_parent: Reference
---""",
        f"""# Inbox card fields

Schema fields for Inbox cards under `inbox/`. The source of truth is
`src/.memoria/schemas/types/`; this generated page is the lookup view for the
PI-facing card shapes. The daily **Needs me** view embeds only proposed
`candidate`, `gap`, and `work-prompt` cards. `flag` and `alert` cards remain
Inbox cards, but Maintenance owns their drift and health views unless they raise
a work prompt.

Regenerate with `python scripts/gen_reference_refs.py --write`; edit the type
schemas, not this page.

{render_inbox_cards().rstrip()}

## Related

- The universal field grammar: [Frontmatter fields](frontmatter.md)
- The board state machine: [Kanban board reference](kanban-board.md)
- Why these shapes exist: [The honesty card](../explanation/kanban-board/honesty-card.md)
""",
    )


def flatten(prefix: str, value: Any) -> list[tuple[str, Any]]:
    if isinstance(value, dict):
        rows: list[tuple[str, Any]] = []
        for key, nested in value.items():
            rows.extend(flatten(f"{prefix}.{key}" if prefix else str(key), nested))
        return rows
    return [(prefix, value)]


def render_configuration() -> str:
    layout = folders()
    home_map = layout.get("homes") or {}
    lines = [
        f"Generated from `{(SCHEMAS / 'folders.yaml').relative_to(ROOT)}`.",
        "",
        "## Folder controls",
        "",
        "| Setting | Value |",
        "| --- | --- |",
        f"| Categories | {cell(layout.get('categories') or [])} |",
        f"| Gated prefixes | {cell(layout.get('gated_prefixes') or [])} |",
        f"| Transient prefixes | {cell(layout.get('transient_prefixes') or [])} |",
        f"| Skeleton entries | {cell(len(layout.get('skeleton') or []))} |",
        "",
        "## Type homes",
        "",
        "| Type | Folder |",
        "| --- | --- |",
    ]
    for doc_type, folder in sorted(home_map.items()):
        lines.append(f"| {cell(doc_type)} | {cell(folder)} |")

    lines.extend(
        [
            "",
            "## Calibration blocks",
            "",
            "| Block | Keys |",
            "| --- | --- |",
        ]
    )
    for key, value in calibration().items():
        keys = sorted(value.keys()) if isinstance(value, dict) else []
        lines.append(f"| {cell(key)} | {cell(keys)} |")
    return generated_block(lines)


def render_configuration_page() -> str:
    return generated_page(
        """---
title: Memoria configuration
parent: System and infrastructure
grand_parent: Reference
---""",
        f"""# Memoria configuration

Memoria configuration is split across repo-authored source, rendered Hermes
profiles, runtime vault files, Obsidian plugin files, and per-machine secrets.
This generated page is the ownership ledger; field-level contracts stay in the
linked reference pages and schema files.

Regenerate with `python scripts/gen_reference_refs.py --write`; edit source
files or this generator, not this page.

## Configuration surfaces

| Surface | Source | Installed location | Owner | Edit policy | Validator |
| --- | --- | --- | --- | --- | --- |
| Hermes profile config | `src/.memoria/profiles/memoria-*/config.yaml` | `~/.hermes/profiles/memoria-*/config.yaml` | Memoria | Edit source; regenerate capability blocks from `tool-registry.yaml`; then redeploy profiles | `tests/test_profiles.py` |
| Profile metadata | `src/.memoria/profiles/memoria-*/distribution.yaml` | Hermes profile manifest | Memoria | Edit source | `tests/test_profiles.py` |
| Profile identity | `src/.memoria/profiles/memoria-*/SOUL.md` | Hermes profile directory | Memoria, with PI customization inside release limits | Edit source; reconcile runtime drift intentionally | profile docs and tests |
| Bundled profile skills | `src/.memoria/profiles/*/skills/` | Hermes profile directory | Memoria | Edit source | profile tests |
| Tool capability registry | `src/.memoria/tool-registry.yaml` | vault source and runtime vault | Memoria | Edit source | `tests/test_profiles.py` |
| Lane policy overlays | `src/.memoria/lane-overrides/*.yaml` | vault source and runtime vault | Memoria | Edit source | policy tests |
| Policy gate plugin | `src/.memoria/plugins/memoria-policy-gate/plugin.yaml` | Hermes profile plugins | Memoria | Edit source | policy tests |
| MCP server config | embedded in each profile `config.yaml` | Hermes profile config | Memoria | Edit source, then redeploy profiles | profile and MCP tests |
| MCP Python dependencies | `src/.memoria/mcp/requirements*.txt` | `<vault>/.memoria/.venv` | Memoria | Edit source; reinstall deps | installer tests |
| Project hints | `src/.memoria/project-hints.yaml.example` | `<vault>/.memoria/project-hints.yaml` | PI | Copy-on-first-use; absent means manual tagging | project-hints guide and linter checks |
| Schema config | `src/.memoria/schemas/**` | vault source and runtime vault | Memoria | Edit source | linter and schema tests |
| Calibration | `src/.memoria/schemas/calibration.yaml` | vault source and runtime vault | Memoria | Edit source | calibration and linter tests |
| Obsidian plugin settings | `src/.obsidian/plugins/**` | runtime vault `.obsidian/plugins/**` | Memoria except local secrets | Shipped config; reconcile intentionally | plugin docs and status checks |
| Local REST API secrets | example files only | runtime plugin `data.json` plus profile `.env` | PI machine | Never commit live secrets | setup docs |
| Profile environment variables | `env_requires` in each profile's `distribution.yaml` | `~/.hermes/profiles/<profile>/.env` or `%LOCALAPPDATA%\\hermes\\profiles\\<profile>\\.env` | PI machine | Never commit; seed from shared Hermes env | installer smoke |
| Shared Hermes environment seed | not in repo | `~/.hermes/.env` or `%LOCALAPPDATA%\\hermes\\.env` | PI machine | Never commit; rerun profiles-only after changes | installer propagation |
| qmd index config and state | scripts plus runtime collection | `.qmd/` and runtime qmd store | generated | Rebuild; do not hand-edit | qmd scripts |
| Cron wrappers | `src/.memoria/scripts/*.sh` | vault source and Hermes cron commands | Memoria | Edit source | shellcheck |

{render_configuration().rstrip()}

## Rendered versus authored

`src/.memoria/profiles/**/config.yaml` is checked-in source. Its mechanical
capability blocks are generated from `src/.memoria/tool-registry.yaml` by
`scripts/render_profile_configs.py`; profile-specific server wiring and model
placeholders remain in the profile config.

Profile `.env` files are user-owned secret stores. They are not source, and
Hermes profile runs read the profile-local `.env` rather than inheriting a
global fallback.

Memoria profiles do not use standalone `mcp.json`. MCP servers live in profile
`config.yaml`; profile redeploy removes any legacy
`~/.hermes/profiles/memoria-*/mcp.json` stale state.

## Required redeploys

| Change | Command |
| --- | --- |
| Profile config, tools, MCP servers, or model overlay | `bash scripts/install.sh --profiles-only --vault ~/Memoria-test` or `.\\scripts\\install.ps1 -ProfilesOnly -Vault "$env:USERPROFILE\\Memoria-test"` |
| Secrets added or rotated in the shared Hermes `.env` | `bash scripts/install.sh --profiles-only --vault ~/Memoria-test` or `.\\scripts\\install.ps1 -ProfilesOnly -Vault "$env:USERPROFILE\\Memoria-test"` |
| Schema or vault source config | reinstall or refresh the vault, then run the linter |
| qmd index inputs | `bash scripts/qmd-codebase-index.sh --embed` |

Use the production vault path instead of `~/Memoria-test` only when you are
deploying a real runtime vault. Development verification uses the test vault.

## Never commit

- `OBSIDIAN_API_KEY`, model provider keys, or API tokens.
- Profile `.env` files.
- Local REST API live `data.json`.
- Generated qmd indexes.
- Runtime vault state, logs, and local diagnostics.

## Related references

- Profile surfaces and capability gates: [Profile capabilities](profile-capabilities.md)
- Installer rendering and environment overlays: [Installer (bootstrap)](installer.md)
- Write-gate contract: [Policy MCP](policy-mcp.md)
- Obsidian plugin files: [Obsidian plugin data files](obsidian-plugin-data-files.md)
- Obsidian plugin settings: [Obsidian plugin settings](obsidian-plugin-settings.md)
- External integrations: [External integrations](integrations.md)
- Frontmatter fields: [Frontmatter fields](frontmatter.md)
- Calibration thresholds: [Calibration](calibration.md)
- Search and qmd: [Search](search.md)
""",
    )


def render_calibration() -> str:
    lines = [
        f"Generated from `{(SCHEMAS / 'calibration.yaml').relative_to(ROOT)}`.",
        "",
        "| Path | Value |",
        "| --- | --- |",
    ]
    for path, value in flatten("", calibration()):
        lines.append(f"| {cell(path)} | {cell(value)} |")
    return generated_block(lines)


def render_calibration_page() -> str:
    return generated_page(
        """---
title: Calibration
parent: Agents and control
grand_parent: Reference
---""",
        f"""# Calibration

`src/.memoria/schemas/calibration.yaml` is the source of truth for shared
thresholds. Every calibrated value follows the same discipline: grounded in real
Memoria data, bounded by an explicit error budget, recalibrated on drift, and
shadow-first before it affects routing or automation.

Regenerate with `python scripts/gen_reference_refs.py --write`; edit
`src/.memoria/schemas/calibration.yaml`, not this page.

## Production rule

A score may affect production behavior only when all of these are true:

- `production_enabled: true`
- the relevant threshold fields are non-null
- `grounding_dataset` names the reviewed dataset or log slice used to fit the
  thresholds
- `model_version` pins the model, scorer, or upstream source version whose scores
  were calibrated
- the sample-count and error-budget fields in that block are satisfied

If any threshold is `null`, the score is report-only. It may log shadow telemetry
or appear in a review surface, but it must not auto-accept, auto-defer, hide,
merge, block, or reorder canonical work.

{render_calibration().rstrip()}

## Drift

Recalibrate any enabled block when the scoring model, embedding model, upstream
classification source, prompt, or feature extraction changes. Until recalibration
passes the same sample and error-budget checks, set `production_enabled: false`
and return the score to shadow mode.
""",
    )


RENDERERS = {
    "docs/reference/document-types.md": render_document_types,
    "docs/reference/frontmatter.md": render_frontmatter,
    "docs/reference/inbox-card-fields.md": render_inbox_cards,
    "docs/reference/configuration.md": render_configuration,
    "docs/reference/calibration.md": render_calibration,
}

FULL_PAGE_RENDERERS = {
    "docs/reference/document-types.md": render_document_types_page,
    "docs/reference/frontmatter.md": render_frontmatter_page,
    "docs/reference/inbox-card-fields.md": render_inbox_cards_page,
    "docs/reference/configuration.md": render_configuration_page,
    "docs/reference/calibration.md": render_calibration_page,
}


def update(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ValueError(f"{path}: missing generated block markers")
    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    return before.rstrip() + "\n\n" + block.rstrip() + "\n\n" + after.lstrip("\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for relative in DOCS:
        path = ROOT / relative
        if relative in FULL_PAGE_RENDERERS:
            expected = FULL_PAGE_RENDERERS[relative]()
        else:
            expected = update(path, RENDERERS[relative]())
        current = path.read_text(encoding="utf-8")
        if args.write:
            path.write_text(expected, encoding="utf-8")
        elif current != expected:
            stale.append(relative)

    if args.check and stale:
        raise SystemExit(
            "schema-backed references are stale; run scripts/gen_reference_refs.py --write: "
            + ", ".join(stale)
        )
    print("gen-reference-refs: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
