#!/usr/bin/env python3
"""Generate schema-backed reference pages and tables."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
SCHEMAS = ROOT / "vault-template/.memoria/schemas"
TYPES = SCHEMAS / "types"
START = "<!-- REFERENCE:START -->"
END = "<!-- REFERENCE:END -->"
GENERATED = "<!-- Generated by scripts/gen_reference_refs.py; edit schema sources instead. -->"
GENERATED_PAGE = (
    "<!-- Generated by scripts/gen_reference_refs.py; edit schema sources or generator text "
    "instead. -->"
)
CATEGORY_ORDER = ("catalog", "knowledge", "capabilities")
CATEGORY_LABELS = {
    "catalog": "Catalog Concepts",
    "knowledge": "Knowledge Concepts",
    "capabilities": "Capability Concepts",
}
DOCS = (
    "docs/reference/document-types.md",
    "docs/reference/frontmatter.md",
    "docs/reference/inbox-card-fields.md",
    "docs/reference/configuration.md",
    "docs/reference/calibration.md",
)


def load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def type_schemas() -> list[dict[str, Any]]:
    rows = [load_yaml(path) for path in sorted(TYPES.glob("*.yaml"))]
    return sorted(
        rows,
        key=lambda row: (
            CATEGORY_ORDER.index(row["category"])
            if row["category"] in CATEGORY_ORDER
            else len(CATEGORY_ORDER),
            row["type"],
        ),
    )


def folders() -> dict[str, Any]:
    return load_yaml(SCHEMAS / "folders.yaml")


def calibration() -> dict[str, Any]:
    return load_yaml(SCHEMAS / "calibration.yaml")


def cell(value: Any) -> str:
    if value is None:
        return "`null`"
    if value == [] or value == {}:
        return "-"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, (int, float)):
        return f"`{value}`"
    if isinstance(value, list):
        return " · ".join(f"`{item}`" for item in value) or "-"
    escaped = str(value).replace("|", "\\|")
    return f"`{escaped}`"


def field_names(fields: Any) -> str:
    return cell(list((fields or {}).keys()))


def check_status(schema: dict[str, Any]) -> str:
    return cell((schema.get("enums") or {}).get("check_status") or [])


def enum_values(schema: dict[str, Any], kind: str) -> str:
    if not kind.startswith("enum:"):
        return "-"
    return cell((schema.get("enums") or {}).get(kind.split(":", 1)[1]) or [])


def generated_block(lines: list[str]) -> str:
    return "\n".join([START, GENERATED, "", *lines, "", END, ""])


def generated_page(frontmatter: str, body: str) -> str:
    return frontmatter.strip() + "\n\n" + GENERATED_PAGE + "\n\n" + body.strip() + "\n"


def render_document_types() -> str:
    all_types = type_schemas()
    home_map = folders().get("homes") or {}
    by_category: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for schema in all_types:
        by_category[schema["category"]].append(schema)

    counts = ", ".join(
        f"{CATEGORY_LABELS[category]}: {len(by_category[category])}"
        for category in CATEGORY_ORDER
        if by_category[category]
    )
    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}` and `{(SCHEMAS / 'folders.yaml').relative_to(ROOT)}`.",
        f"Total types: **{len(all_types)}** ({counts}).",
        "",
    ]
    for category in CATEGORY_ORDER:
        rows = by_category.get(category)
        if not rows:
            continue
        lines.extend(
            [
                f"## {CATEGORY_LABELS[category]} ({len(rows)})",
                "",
                "| Type | Folder | Gated | Initial check status | Check status values | Required fields | Required-any | Optional fields |",
                "| --- | --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for schema in rows:
            doc_type = schema["type"]
            lines.append(
                "| "
                + " | ".join(
                    [
                        cell(doc_type),
                        cell(home_map.get(doc_type)),
                        cell(schema.get("gated", False)),
                        cell(schema.get("initial_check_status")),
                        check_status(schema),
                        field_names(schema.get("required")),
                        cell(schema.get("required_any") or []),
                        field_names(schema.get("optional")),
                    ]
                )
                + " |"
            )
        lines.append("")
    return generated_block(lines)


def render_document_types_page() -> str:
    return generated_page(
        """---
title: Document types
parent: Vault data model
grand_parent: Reference
---""",
        f"""# Document types

The Concept schemas are authoritative: every type is defined by one YAML file
under `vault-template/.memoria/schemas/types`, and the type-to-folder map lives
in `vault-template/.memoria/schemas/folders.yaml`.
This generated page is the lookup view for folder homes, check status, and
field presence. For field semantics, see [Frontmatter fields](frontmatter.md).

Regenerate with `python scripts/gen_reference_refs.py --write`; edit the schema
sources, not this page.

{render_document_types().rstrip()}

## Related

- Field kinds, check status values, enums, and per-type field inventory:
  [Frontmatter fields](frontmatter.md)
- Retired Inbox card contracts: [Inbox card fields](inbox-card-fields.md)
- The folder tree the homes map into: [On-disk layout](on-disk-layout.md)
- What enforces the schemas: [Linter: detectors and auto-fix](linter.md) and
  [Policy gate](policy-mcp.md)
""",
    )


def render_frontmatter() -> str:
    schemas = type_schemas()
    check_status_groups: dict[str, list[str]] = defaultdict(list)
    for schema in schemas:
        check_status_groups[check_status(schema)].append(schema["type"])

    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}`.",
        "",
        "## Check status subsets",
        "",
        "| Check status subset | Types |",
        "| --- | --- |",
    ]
    for subset, names in sorted(check_status_groups.items(), key=lambda item: item[0]):
        lines.append(f"| {subset} | {cell(names)} |")

    lines.extend(
        [
            "",
            "## Enum values",
            "",
            "| Type | Enum | Values |",
            "| --- | --- | --- |",
        ]
    )
    for schema in schemas:
        for enum_name, values in sorted((schema.get("enums") or {}).items()):
            lines.append(f"| {cell(schema['type'])} | {cell(enum_name)} | {cell(values)} |")

    lines.extend(
        [
            "",
            "## Per-type fields",
            "",
            "| Type | Required | Required-any | Optional |",
            "| --- | --- | --- | --- |",
        ]
    )
    for schema in schemas:
        lines.append(
            f"| {cell(schema['type'])} | {field_names(schema.get('required'))} | "
            f"{cell(schema.get('required_any') or [])} | {field_names(schema.get('optional'))} |"
        )
    return generated_block(lines)


def render_frontmatter_page() -> str:
    return generated_page(
        """---
title: Frontmatter fields
parent: Vault data model
grand_parent: Reference
---""",
        f"""# Frontmatter fields

The frontmatter contract for every typed document. **The single source is
`.memoria/schemas/`**: per-document-type field schemas in
`vault-template/.memoria/schemas/types`, the type-to-folder map in
`vault-template/.memoria/schemas/folders.yaml`, and calibrated thresholds in
`vault-template/.memoria/schemas/calibration.yaml`. The shared loader/validator is
`src/memoria_vault/runtime/subsystems/lib/schema.py`; the Linter, pre-commit hook, and
installer-skeleton tests all read it. This generated page explains the grammar
and universal fields; the per-type tables live in [Document types](document-types.md).

Regenerate with `python scripts/gen_reference_refs.py --write`; edit schema
sources or this generator, not this page.

## The field-kind grammar

Each type schema declares `required:` and `optional:` maps of `field: kind`,
plus an `enums:` block and optionally `required_any:`. The kinds:

| Kind | Accepts |
| --- | --- |
| `str` | a string |
| `int` | an integer (not a bool) |
| `bool` | a boolean |
| `date` | a YAML date or an ISO-8601 date string |
| `list` | a YAML sequence |
| `map` | a YAML mapping |
| `literal:<value>` | exactly that value; for example, `type: literal:source` |
| `enum:<name>` | one of the values the schema's `enums.<name>` lists |

Unknown extra fields are **allowed**. A schema example (`types/source.yaml`):

```yaml
type: source
category: catalog
gated: false
initial_check_status: unchecked
enums:
  check_status: [unchecked, checked, quarantined]
  item_type:
    [article, book, webpage, dataset, repository, software, audio, video, note, report]
required:
  type: literal:source
  check_status: enum:check_status
  title: str
  description: str
  source_id: str
optional:
  resource: str
  item_type: enum:item_type
  links: map
  tags: list
```

{render_frontmatter().rstrip()}

## Creation forms

Obsidian Modal Forms are committed as plugin `data.json`. They are UI entry
points, not schema authority; the Concept schemas above remain the validator
contract. Forms may collect values that are not frontmatter fields. The writer
maps those values into the body or structured frontmatter before validation.

## Display order and grouping

The schema validates field presence and kind; display order is a shipped-vault
convention. Templates and deterministic emitters put fields in this order:

1. Human identity: `title` or `name`.
2. Schema identity and read state: `type`, then `check_status`.
3. Human summary and pointer fields: `description`, `resource`, `source_id`.
4. Type-specific state and references.
5. Relations and classification: `links`, `tags`, and type-specific maps.

Obsidian does not have a global property-order schema file, so the shipped
templates, emitters, and Bases carry this convention directly.

## `check_status`

Every Concept carries `check_status`, drawn from the same read-state enum:

```text
unchecked → checked → quarantined
```

`unchecked` is ingestible but not promoted as checked knowledge. `checked` is
the read barrier for machine-owned records and curated PI views. `quarantined`
records failed validation, provenance, or foreign-write checks and stay out of
normal read surfaces until repaired.

## Links and resources

Concepts use `resource` for the backing source pointer when one exists. `links`
is type-specific: some schemas use a list, others a map. The generated field
inventory above owns the exact current shape.

## Other universal fields

| Field | Kind | Notes |
| --- | --- | --- |
| `type` | `literal:` | Pins the note to its schema. Set at creation; never changed. |
| `title` | `str` | Human-readable Concept title. |
| `check_status` | `enum` | Read-state gate: `unchecked`, `checked`, or `quarantined`. |
| `description` | `str` | Required on all shipped Concept types except `note`, where it is optional. |
| `resource` | `str` | Optional backing-resource pointer. |
| `tags` | `list` | Optional local classification where the type supports it. |

## Enforcement

| Where | What |
| --- | --- |
| Pre-commit hook | Every staged `.md` Concept must pass its type schema. |
| Daily Linter cron | The `schema-check` and `frontmatter-link` detectors monitor between commits. |
| Exemptions | Most `system/` infrastructure and vault-root navigation pages are untyped and exempt. |

## Related

- The per-document-type field tables: [Document types](document-types.md)
- The controlled classification values: [Vocabulary](vocabulary.md)
- What validates this contract: [Linter: detectors and auto-fix](linter.md)
- Where the schema files live: [On-disk layout](on-disk-layout.md)
""",
    )


def render_inbox_cards() -> str:
    lines = [
        f"Generated from `{TYPES.relative_to(ROOT)}`.",
        "",
        "Alpha.11 has no durable Inbox card Concept types. Attention and action state are",
        "generated operational surfaces, not a separate checked Concept family.",
    ]
    return generated_block(lines)


def render_inbox_cards_page() -> str:
    return generated_page(
        """---
title: Inbox card fields
parent: Vault data model
grand_parent: Reference
---""",
        f"""# Inbox card fields

Alpha.11 removes durable Inbox card schemas from the vault skeleton. The source
of truth remains `vault-template/.memoria/schemas/types/`; this page is kept as a
stable reference target and now records that no Inbox card Concept family ships.

Regenerate with `python scripts/gen_reference_refs.py --write`; edit the type
schemas, not this page.

{render_inbox_cards().rstrip()}

## Related

- The universal field grammar: [Frontmatter fields](frontmatter.md)
- Current Concept types: [Document types](document-types.md)
""",
    )


def flatten(prefix: str, value: Any) -> list[tuple[str, Any]]:
    if isinstance(value, dict):
        rows: list[tuple[str, Any]] = []
        for key, nested in value.items():
            rows.extend(flatten(f"{prefix}.{key}" if prefix else str(key), nested))
        return rows
    return [(prefix, value)]


def render_configuration() -> str:
    layout = folders()
    home_map = layout.get("homes") or {}
    lines = [
        f"Generated from `{(SCHEMAS / 'folders.yaml').relative_to(ROOT)}`.",
        "",
        "## Folder controls",
        "",
        "| Setting | Value |",
        "| --- | --- |",
        f"| Categories | {cell(layout.get('categories') or [])} |",
        f"| Bundle roots | {cell(layout.get('bundle_roots') or [])} |",
        f"| Machine staging roots | {cell(layout.get('machine_staging_roots') or [])} |",
        f"| Quarantine root | {cell(layout.get('quarantine_root'))} |",
        f"| Gated prefixes | {cell(layout.get('gated_prefixes') or [])} |",
        f"| Transient prefixes | {cell(layout.get('transient_prefixes') or [])} |",
        f"| Skeleton entries | {cell(len(layout.get('skeleton') or []))} |",
        "",
        "## Type homes",
        "",
        "| Type | Folder |",
        "| --- | --- |",
    ]
    for doc_type, folder in sorted(home_map.items()):
        lines.append(f"| {cell(doc_type)} | {cell(folder)} |")

    lines.extend(
        [
            "",
            "## Calibration blocks",
            "",
            "| Block | Keys |",
            "| --- | --- |",
        ]
    )
    for key, value in calibration().items():
        keys = sorted(value.keys()) if isinstance(value, dict) else []
        lines.append(f"| {cell(key)} | {cell(keys)} |")
    return generated_block(lines)


def render_configuration_page() -> str:
    return generated_page(
        """---
title: Memoria configuration
parent: System and infrastructure
grand_parent: Reference
---""",
        f"""# Memoria configuration

Memoria configuration is split across repo-authored source, runtime vault files,
Obsidian plugin files, and per-machine secrets.
This generated page is the ownership ledger; field-level contracts stay in the
linked reference pages and schema files.

Regenerate with `python scripts/gen_reference_refs.py --write`; edit source
files or this generator, not this page.

## Configuration surfaces

| Surface | Source | Installed location | Owner | Edit policy | Validator |
| --- | --- | --- | --- | --- | --- |
| Policy gate plugin | `vault-template/.memoria/plugins/memoria-policy-gate/plugin.yaml` | workspace policy package for optional adapters | Memoria | Edit source | policy tests |
| Runtime Python package | `pyproject.toml` + `src/memoria_vault/**` | `<vault>/.memoria/.venv` | Memoria | Edit source; reinstall runtime | installer tests |
| Project hints | `vault-template/.memoria/project-hints.yaml.example` | `<vault>/.memoria/project-hints.yaml` | PI | Copy-on-first-use; absent means manual tagging | project-hints guide and linter checks |
| Schema config | `vault-template/.memoria/schemas/**` | vault source and runtime vault | Memoria | Edit source | linter and schema tests |
| Calibration | `vault-template/.memoria/schemas/calibration.yaml` | vault source and runtime vault | Memoria | Edit source | calibration and linter tests |
| Obsidian plugin settings | `vault-template/.obsidian/plugins/**` | runtime vault `.obsidian/plugins/**` | Memoria except local secrets | Shipped config; reconcile intentionally | plugin docs and status checks |
| Local REST API secrets | example files only | runtime plugin `data.json` when the optional Obsidian adapter is used | PI machine | Never commit live secrets | setup docs |
| qmd index config and state | scripts plus runtime collection | `.qmd/` and runtime qmd store | generated | Rebuild; do not hand-edit | qmd scripts |
| Scheduled-task wrappers | `vault-template/.memoria/scripts/*.sh` | workspace source for operator-managed scheduled tasks | Memoria | Edit source | shellcheck |

{render_configuration().rstrip()}

## Required redeploys

| Change | Command |
| --- | --- |
| Schema or vault source config | reinstall or refresh the vault, then run the linter |
| qmd index inputs | `bash scripts/qmd-codebase-index.sh --embed` |

Use the production vault path instead of `~/Memoria-test` only when you are
deploying a real runtime vault. Development verification uses the test vault.

## Never commit

- `OBSIDIAN_API_KEY`, model provider keys, or API tokens.
- Local REST API live `data.json`.
- Generated qmd indexes.
- Runtime vault state, logs, and local diagnostics.

## Related references

- Installer rendering and environment overlays: [Installer (bootstrap)](installer.md)
- Write-gate contract: [Policy gate](policy-mcp.md)
- Obsidian plugin files: [Obsidian plugin data files](obsidian-plugin-data-files.md)
- Obsidian plugin settings: [Obsidian plugin settings](obsidian-plugin-settings.md)
- External integrations: [External integrations](integrations.md)
- Frontmatter fields: [Frontmatter fields](frontmatter.md)
- Calibration thresholds: [Calibration](calibration.md)
- Search and qmd: [Search](search.md)
""",
    )


def render_calibration() -> str:
    lines = [
        f"Generated from `{(SCHEMAS / 'calibration.yaml').relative_to(ROOT)}`.",
        "",
        "| Path | Value |",
        "| --- | --- |",
    ]
    for path, value in flatten("", calibration()):
        lines.append(f"| {cell(path)} | {cell(value)} |")
    return generated_block(lines)


def render_calibration_page() -> str:
    return generated_page(
        """---
title: Calibration
parent: Agents and control
grand_parent: Reference
---""",
        f"""# Calibration

`vault-template/.memoria/schemas/calibration.yaml` is the source of truth for shared
thresholds. Every calibrated value follows the same discipline: grounded in real
Memoria data, bounded by an explicit error budget, recalibrated on drift, and
shadow-first before it affects routing or automation.

Regenerate with `python scripts/gen_reference_refs.py --write`; edit
`vault-template/.memoria/schemas/calibration.yaml`, not this page.

## Production rule

A score may affect production behavior only when all of these are true:

- `production_enabled: true`
- the relevant threshold fields are non-null
- `grounding_dataset` names the reviewed dataset or log slice used to fit the
  thresholds
- `model_version` pins the model, scorer, or upstream source version whose scores
  were calibrated
- the sample-count and error-budget fields in that block are satisfied

If any threshold is `null`, the score is report-only. It may log shadow telemetry
or appear in a review surface, but it must not auto-accept, auto-defer, hide,
merge, block, or reorder canonical work.

{render_calibration().rstrip()}

## Drift

Recalibrate any enabled block when the scoring model, embedding model, upstream
classification source, prompt, or feature extraction changes. Until recalibration
passes the same sample and error-budget checks, set `production_enabled: false`
and return the score to shadow mode.
""",
    )


RENDERERS = {
    "docs/reference/document-types.md": render_document_types,
    "docs/reference/frontmatter.md": render_frontmatter,
    "docs/reference/inbox-card-fields.md": render_inbox_cards,
    "docs/reference/configuration.md": render_configuration,
    "docs/reference/calibration.md": render_calibration,
}

FULL_PAGE_RENDERERS = {
    "docs/reference/document-types.md": render_document_types_page,
    "docs/reference/frontmatter.md": render_frontmatter_page,
    "docs/reference/inbox-card-fields.md": render_inbox_cards_page,
    "docs/reference/configuration.md": render_configuration_page,
    "docs/reference/calibration.md": render_calibration_page,
}


def update(path: Path, block: str) -> str:
    text = path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise ValueError(f"{path}: missing generated block markers")
    before, rest = text.split(START, 1)
    _, after = rest.split(END, 1)
    return before.rstrip() + "\n\n" + block.rstrip() + "\n\n" + after.lstrip("\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for relative in DOCS:
        path = ROOT / relative
        if relative in FULL_PAGE_RENDERERS:
            expected = FULL_PAGE_RENDERERS[relative]()
        else:
            expected = update(path, RENDERERS[relative]())
        current = path.read_text(encoding="utf-8")
        if args.write:
            path.write_text(expected, encoding="utf-8")
        elif current != expected:
            stale.append(relative)

    if args.check and stale:
        raise SystemExit(
            "schema-backed references are stale; run scripts/gen_reference_refs.py --write: "
            + ", ".join(stale)
        )
    print("gen-reference-refs: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
