#!/usr/bin/env python3
"""Generate the volatile profile-capability reference page."""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs/reference/profiles.md"
PROFILES = ROOT / "src/.memoria/profiles"
LANES = ROOT / "src/.memoria/lane-overrides"
TASKS_MCP = ROOT / "src/.memoria/mcp/tasks_mcp.py"
START = "<!-- PROFILES:START -->"
END = "<!-- PROFILES:END -->"
GENERATED = "<!-- Generated by scripts/gen_profiles_ref.py; edit profile sources instead. -->"
GENERATED_PAGE = (
    "<!-- Generated by scripts/gen_profiles_ref.py; edit profile sources or generator text "
    "instead. -->"
)
ORDER = (
    "memoria-copi",
    "memoria-librarian",
    "memoria-writer",
    "memoria-peer-reviewer",
    "memoria-engineer",
)

sys.path.insert(0, str(ROOT / "scripts"))
from render_profile_configs import load_registry, toolsets_for


def _load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _profiles() -> list[str]:
    names = sorted(p.name for p in PROFILES.iterdir() if p.is_dir())
    return [name for name in ORDER if name in names] + [name for name in names if name not in ORDER]


def _lane_override(profile: str) -> dict[str, Any]:
    path = LANES / f"{profile.removeprefix('memoria-')}.yaml"
    return _load_yaml(path) if path.is_file() else {}


def _lane_profile() -> dict[str, str]:
    tree = ast.parse(TASKS_MCP.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(
            isinstance(target, ast.Name) and target.id == "LANE_PROFILE" for target in node.targets
        ):
            return ast.literal_eval(node.value)
    raise ValueError("tasks_mcp.py does not define LANE_PROFILE")


def _cell(value: object) -> str:
    if isinstance(value, list):
        value = ", ".join(f"`{item}`" for item in value) or "None"
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return text or "None"


def _skills(profile: str) -> list[str]:
    root = PROFILES / profile / "skills"
    return sorted(p.name for p in root.iterdir() if p.is_dir()) if root.is_dir() else []


def render_tables() -> str:
    registry = load_registry()
    lines = [
        START,
        GENERATED,
        "",
        "## The five profiles",
        "",
        "This block is generated from `src/.memoria/profiles`, "
        "`src/.memoria/lane-overrides`, `src/.memoria/tool-registry.yaml`, and "
        "`src/.memoria/mcp/tasks_mcp.py`.",
        "",
        "### Package metadata",
        "",
        "| Profile | Version | Hermes requirement | Invocation | Write scope |",
        "| --- | --- | --- | --- | --- |",
    ]
    for profile in _profiles():
        dist = _load_yaml(PROFILES / profile / "distribution.yaml")
        lane = _lane_override(profile)
        routing = lane.get("routing") or {}
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{profile}`",
                    _cell(dist.get("version")),
                    _cell(dist.get("hermes_requires")),
                    f"`{routing.get('invocation', 'interactive_only')}`",
                    _cell(routing.get("write_scope") or []),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "### Lane routing",
            "",
            "| Task lane | Profile |",
            "| --- | --- |",
        ]
    )
    for lane, profile in sorted(_lane_profile().items()):
        lines.append(f"| `{lane}` | `{profile}` |")

    lines.extend(
        [
            "",
            "### MCP servers and toolsets",
            "",
            "| Profile | MCP servers | Platform toolsets |",
            "| --- | --- | --- |",
        ]
    )
    for profile in _profiles():
        config = _load_yaml(PROFILES / profile / "config.yaml")
        servers = sorted((config.get("mcp_servers") or {}).keys())
        lines.append(
            f"| `{profile}` | {_cell(servers)} | {_cell(toolsets_for(profile, registry))} |"
        )

    lines.extend(
        [
            "",
            "### Lane policy",
            "",
            "| Profile | Required controls | Explicitly denied write scopes |",
            "| --- | --- | --- |",
        ]
    )
    for profile in _profiles():
        policy = _lane_override(profile).get("policy") or {}
        lines.append(
            f"| `{profile}` | {_cell(policy.get('require') or [])} | "
            f"{_cell((policy.get('deny') or {}).get('write') or [])} |"
        )

    lines.extend(
        [
            "",
            "### Bundled skills",
            "",
            "| Profile | Count | Skills |",
            "| --- | ---: | --- |",
        ]
    )
    for profile in _profiles():
        skills = _skills(profile)
        lines.append(f"| `{profile}` | {len(skills)} | {_cell(skills)} |")

    lines.extend(["", END, ""])
    return "\n".join(lines)


def render_page() -> str:
    return (
        """---
title: Profile capabilities
parent: Agents and control
grand_parent: Reference
---

"""
        + GENERATED_PAGE
        + f"""

# Profile capabilities

The five Memoria profiles ([ADR-48](../adr/48-copi-and-agent-consolidation.md)):
posture, board lanes, write scopes, MCP servers, and bundled skills. Every value
on this page is read from the shipped sources: profile packages under
`src/.memoria/profiles`, lane ceilings under `src/.memoria/lane-overrides`, and
the per-profile tool allowlist in `src/.memoria/tool-registry.yaml`.

Regenerate with `python scripts/gen_profiles_ref.py --write`; edit the profile,
lane, and tool-registry sources, not this page.

{render_tables().rstrip()}

## Related

- The write-gate decisions and lane-override shape: [Policy MCP](policy-mcp.md)
- The board the lanes pull from: [Kanban board reference](kanban-board.md)
- The CLI surface per profile: [Hermes CLI](hermes-cli.md)
- Where profiles live on disk: [On-disk layout](on-disk-layout.md)
"""
    ).strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    expected = render_page()
    current = DOC.read_text(encoding="utf-8")
    if args.write:
        DOC.write_text(expected, encoding="utf-8")
        return 0
    if args.check and current != expected:
        raise SystemExit(
            "docs/reference/profiles.md is stale; run scripts/gen_profiles_ref.py --write"
        )
    print("gen-profiles-ref: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
