#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SECTION="all"

usage() {
  cat <<'USAGE'
Usage: scripts/human-acceptance-wizard.sh [--section all|plugin|canvas|loop13]

Guide the PI through the remaining human-only acceptance checks. The wizard
does not execute Memoria, SQLite, Git, Obsidian, Zotero, or provider commands.
USAGE
}

while (($#)); do
  case "$1" in
    --section)
      (($# >= 2)) || { usage >&2; exit 2; }
      SECTION="$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
done

case "$SECTION" in
  all) TOTAL_STAGES=31 ;;
  plugin) TOTAL_STAGES=13 ;;
  canvas) TOTAL_STAGES=6 ;;
  loop13) TOTAL_STAGES=12 ;;
  *) usage >&2; exit 2 ;;
esac

umask 077
RUN_LOG="${RUN_LOG:-$(mktemp "${TMPDIR:-/tmp}/memoria-human-acceptance.XXXXXX.md")}"
touch "$RUN_LOG"
chmod 600 "$RUN_LOG"

record() {
  local title="$1" observation=""
  ask observation "Record pass, fail, or blocked evidence (do not enter secrets):"
  {
    printf '## %s\n\n' "$title"
    printf '%s\n\n' "$observation"
  } >> "$RUN_LOG"
}

show_command() {
  say "Do not run this command from the wizard. Copy it into your own terminal after reviewing it."
  printf '\n%s\n\n' "$1"
}

include_section() {
  [[ "$SECTION" == "all" || "$SECTION" == "$1" ]]
}

banner "Memoria human acceptance checks"
say "Run log: $RUN_LOG"
say "Never print or pass a handshake token. Do not automate Obsidian, Zotero, licensing, triage, or stop decisions."
pause "Press Enter after you have read the safety boundary."

if include_section plugin; then
  stage "Open the disposable plugin vault"
  show_command "memoria init --workspace test-vault/u3-plug-manual --yes"
  step "In desktop Obsidian, open test-vault/u3-plug-manual; accept the trust and community-plugin prompts."
  step "Wait for the bottom-right pill to change from Memoria · connecting… to green Memoria · N open within about five seconds; do not type a port or token."
  record "Plugin connection"

  stage "Inspect the Memoria settings"
  step "Open Settings → Memoria. Verify Engine command is memoria and that there is no Server URL or token field."
  record "Memoria settings"

  stage "Prove the token remains outside the vault"
  step "Continue only after the live connection in stage 1 succeeded; otherwise record this check as blocked because a green result would be vacuous."
  show_command "python - <<'PY'
import json
import subprocess
from pathlib import Path

vault = Path(\"test-vault/u3-plug-manual\")
handshake = json.loads(
    subprocess.check_output(
        [\"memoria\", \"handshake\", \"--vault\", str(vault), \"--json\"], text=True
    )
)
token = str(handshake[\"token\"])
hits = [
    path.relative_to(vault).as_posix()
    for path in vault.rglob(\"*\")
    if path.is_file() and token.encode() in path.read_bytes()
]
assert hits == [], hits
PY"
  record "Token non-persistence"

  stage "Inspect the Attention pane"
  step "Click the pill. Verify the right-side ATTENTION pane shows N open · as of HH:MM, loudness dots, ellipsized titles, right-aligned ages, and any block cards pinned on top."
  record "Attention pane"

  stage "Navigate and expand Attention"
  step "Click the pane, press j and k, and verify the highlight moves and clamps at both ends. Press Enter to expand one row, then Enter again to collapse it; only one row may expand at a time."
  step "In the expanded row, verify the kind line, title, evidence inset, body, named text actions with Resolve primary, for/against, tipped by: certainty chip, and meta line."
  record "Attention keyboard navigation"

  stage "Open evidence and queue Resolve"
  step "Open an evidence link and verify its vault note opens."
  record "Evidence opening"
  if confirm "Queue Resolve / resolve-attention now?"; then
    step "Click Resolve and verify the toast Memoria queued resolve-attention: <request id>; with the window focused, verify the card leaves the queue on the next poll (within 30 seconds)."
    record "Resolve queue result"
  else
    record "Resolve queue skipped"
  fi

  stage "Create and complete a rebuttal relation"
  step "With a note open, run Memoria: Relate…. Verify From is pre-filled, From and To filter vault paths, and Relation renders exactly the server-provided roster including rebuttal."
  step "Try Queue edge with To blank and verify relate: To note is required."
  record "Relation dialog and blank-To validation"
  if confirm "Submit the completed rebuttal graph edge now?"; then
    step "Submit a rebuttal, run its queued job, and verify the resulting edge—not only its request id."
    record "Rebuttal edge result"
  else
    record "Rebuttal edge submission skipped"
  fi

  stage "Stop and recover the server"
  if confirm "Stop the disposable vault server now?"; then
    show_command "memoria serve --stop --workspace test-vault/u3-plug-manual"
    step "Unfocus and refocus Obsidian. Verify the pill turns amber Memoria · N open · as of HH:MM; click it to re-handshake, respawn the server, and recover green."
    record "Server recovery"
  else
    record "Server recovery skipped"
  fi

  stage "Mask and restore the engine"
  if confirm "Temporarily mask the engine binary on this disposable check?"; then
    step "Rename the engine binary away using a pipx virtual environment or PATH shadow, then reload Obsidian. Verify gray Memoria · engine missing and install remediation naming the tried command; the vault must remain readable and editable. Restore the binary and click the pill to recover."
    record "Engine missing recovery"
  else
    record "Engine mask skipped"
  fi

  stage "Exercise the server-down state"
  if confirm "Temporarily set the disposable vault Engine command to /bin/false?"; then
    step "In Settings → Memoria, set Engine command to /bin/false, reload, and click the pill at least three times within three minutes. Verify red Memoria · server down with remediation naming the log path and memoria serve --workspace …. Observe and record that there is no infinite silent retry. Restore the original Engine command afterward."
    record "Server-down remediation"
  else
    record "Server-down check skipped"
  fi

  stage "Check both community-theme variants"
  step "Install and inspect one light and one dark community theme. Verify the pill dot, loudness accents, evidence inset, chips, and segmented control follow each theme with no fixed colors."
  record "Community theme variants"

  stage "Observe background polling and refocus"
  step "With the server up, leave Obsidian unfocused for more than two minutes and inspect serve.log for the two-minute cadence. Refocus and verify an immediate poll."
  record "Polling cadence"

  stage "Confirm removal of the disposable vault"
  if confirm "Remove the disposable test-vault/u3-plug-manual vault now?"; then
    step "Verify the exact disposable target is test-vault/u3-plug-manual before deleting anything."
    show_command "rm -rf test-vault/u3-plug-manual"
    record "Disposable plugin vault cleanup"
  else
    record "Disposable plugin vault cleanup skipped"
  fi
fi

if include_section canvas; then
  stage "Capture the Canvas Git baseline"
  step "Before recording the baseline, use a disposable vault under test-vault/ (never a personal vault) with memoria available through the plugin's Engine command."
  show_command "git status --short"
  step "Record the complete pre-run output as the baseline; do not treat an existing file as a plugin write."
  record "Canvas Git baseline"

  stage "Inspect the generated Canvas banner"
  step "Open projects/<p>/argument.canvas in desktop Obsidian. Verify the top-left banner says read-only, regenerated and names Memoria: Fork canvas to scratch."
  record "Generated Canvas banner"

  stage "Queue the Canvas fork"
  if confirm "Queue a fork from the generated Canvas?"; then
    step "Run Memoria: Fork canvas to scratch and record the source argument.canvas path, requested scratch name, request id, and worker result path. If the wrong file is active, the documented failure notice is Open a generated argument.canvas to fork it."
    record "Canvas fork request and result"
  else
    record "Canvas fork skipped"
  fi

  stage "Inspect the editable scratch Canvas"
  step "Open projects/<p>/scratch-<name>.canvas from the worker result. Verify it is editable and has no generated banner. Record both source and scratch paths."
  record "Editable scratch Canvas"

  stage "Draw and observe one divergent edge"
  step "Manually draw exactly one labeled supports edge in the scratch Canvas, then refocus it. Verify Memoria fork: 1 edge(s) diverged. Do not automate drawing or visual review."
  record "Scratch Canvas divergence"

  stage "Graduate the scratch edge and compare Git"
  if confirm "Run graduation for the manually drawn scratch edge?"; then
    step "Run Memoria: Graduate scratch canvas edges. Record source and target paths, request id(s), worker result evidence, and the success notice Memoria queued 1 link edge(s); skipped 0 unresolved. If applicable, record the documented failure notices Open a scratch-*.canvas to graduate its edges. or Memoria could not read this scratch canvas."
    step "After the worker runs, prove the relation exists. Then compare the final Git status to the baseline and record every unaccounted vault file; plugin writes are not an acceptable substitute for worker evidence."
    show_command "git status --short"
    record "Canvas graduation and Git comparison"
  else
    record "Canvas graduation skipped"
  fi
fi

if include_section loop13; then
  LOOP13_STAGE2_ALLOWED=false

  stage "Prepare the licensed inputs and real vault"
  step "Export a licensed 10-work Zotero set as stage1.bib and a licensed 100-work Zotero set as stage2.bib. Record the export provenance and license; do not ask the wizard to open or alter Zotero."
  step "Choose \$HOME/memoria-beta1-vault as a fresh real vault: never test-vault and never an existing personal vault. Confirm the path yourself before running anything."
  say "1000-scale is out of scope (beta.2); this protocol stops at 100 works."
  show_command "VAULT=\"\$HOME/memoria-beta1-vault\"   # fresh real vault; NEVER test-vault/, never an existing personal vault
DB=\"\$VAULT/.memoria/memoria.sqlite\"
REPO=\"\${REPO:-\$PWD}\"                # the memoria checkout, for the frozen retrieval fixtures"
  record "LOOP.13 licensed inputs and fresh vault"

  stage "Initialize, frame, seed, and pass the license gate"
  step "Review and run these commands yourself, in order. Initialization, project framing, and seed installation precede any import."
  show_command "memoria init --workspace \"\$VAULT\" --yes
memoria new project --workspace \"\$VAULT\" \"Acceptance project\"
memoria seed install --workspace \"\$VAULT\" --json
memoria eval seeded-error-verdict --workspace \"\$VAULT\" --json | tee battery.json
python -c \"import json,sys; sys.exit(0 if json.load(open('battery.json'))['result']['passed'] else 1)\" \\
  || { echo \"BLOCKED: no real-vault import until the battery passes (empirical plan Phase 0)\"; exit 1; }"
  warn "A failed seeded-error verdict is a result to record and may block every later real-vault stage; its process exit code alone is not the verdict."
  record "Initialization, project frame, seed, and seeded-error verdict"

  stage "Measure the first grounded answer"
  step "Dispatch the live grounded answer yourself, then read the onboarding-step telemetry measurement of record. Record any provider-policy prompt or latency that breaks session flow; either is a result and may block later stages."
  show_command "memoria ask --workspace \"\$VAULT\" --question \"What does the seed corpus say about retrieval practice?\" --json
sqlite3 \"\$VAULT/.memoria/memoria.sqlite\" \\
  \"SELECT CAST((julianday(MAX(CASE WHEN json_extract(payload_json,'\$.step')='first-answer' THEN ts END)) \\
              - julianday(MIN(CASE WHEN json_extract(payload_json,'\$.step')='init-done' THEN ts END))) * 86400 AS INT) \\
   FROM telemetry_events WHERE event_type='onboarding-step';\" \\
  | xargs -I{} echo \"time_to_first_answer_s={}\" | tee -a staged-import-metrics.txt"
  say "The time-to-first-answer bar is at most 1800 seconds. A larger number is a finding, not a value to conceal or retry away."
  record "Grounded first answer and time-to-first-answer telemetry"

  stage "Inspect the frozen retrieval fixtures"
  step "Run this inspection from the Memoria checkout and preserve its output in the metrics artifact. Copy the exact frozen fixture arguments into later commands; do not retype a query, invent a topic field, or assume a depth."
  show_command "python - \"\$REPO/tests/fixtures/retrieval/cases.yaml\" <<'PY' | tee -a staged-import-metrics.txt
import pathlib, sys, yaml
for row in yaml.safe_load(pathlib.Path(sys.argv[1]).read_text(encoding=\"utf-8\")):
    print(f\"fixture={row['id']} shape={row['shape']} metric={row['metric']} \"
          f\"frozen={row['frozen']} query={row['query']!r}\")
PY"
  record "Frozen fixture ids, arguments, metrics, and declared depth"

  stage "Run the 10-work import and enrichment drain"
  step "Take the event-log watermark first, then run one bulk import of stage1.bib with --enrich. Do not split it into entries and do not perform the import through the wizard."
  show_command "BEFORE=\$(sqlite3 \"\$DB\" \"SELECT COALESCE(MAX(event_id), 0) FROM event_log;\")
memoria work import --workspace \"\$VAULT\" --format bibtex --file stage1.bib --enrich --json \\
  | tee stage1-import.json
sqlite3 \"\$DB\" \\
  \"SELECT payload_json FROM telemetry_events WHERE event_type='import-run.v1' ORDER BY ts DESC LIMIT 1;\" \\
  | tee -a staged-import-metrics.txt
while :; do
  memoria workspace run --workspace \"\$VAULT\" --json | tee -a stage1-enrichment.json \\
    | python -c \"import json,sys; sys.exit(1 if json.load(sys.stdin)['ran'] else 0)\" && break
done
sqlite3 \"\$DB\" \\
  \"SELECT COUNT(*) FROM event_log WHERE event_id > \$BEFORE AND event_type='check-fired'
     AND json_extract(payload_json, '\$.check')='source-retraction';\" \\
  | xargs -I{} echo \"stage1_source_retraction_flags={}\" | tee -a staged-import-metrics.txt"
  warn "A provider-policy prompt or a drain/import latency that breaks session flow is a result to record and may block later stages."
  record "Stage 1 import-run.v1, enrichment drain, and retraction delta"

  stage "Measure retrieval, attention, event log, and storage"
  step "Copy the exact arguments you inspected from the frozen fixture rather than retyping them. The commands below are the plan's frozen 2026-08-02 probes; record the fixture id beside each separate latency."
  show_command "time memoria ask --workspace \"\$VAULT\" --json \\
  --question \"what did the spaced-repetition model find about lag effects\"                    # shape1-spacing-effect-lookup
time memoria ask --workspace \"\$VAULT\" --json \\
  --question \"when do desirable difficulties reverse for high element interactivity material\" # shape1-undesirable-difficulty-boundary
time memoria explore --workspace \"\$VAULT\" \"testing effect boundary conditions\" --depth 1 --json  # shape2-testing-effect-tension
time memoria project explore --workspace \"\$VAULT\" --limit 10 --json                           # not a fixture row: project-surface probe
memoria attention list --workspace \"\$VAULT\" --json | tee stage1-attention.json
memoria attention worklist --workspace \"\$VAULT\" --json | tee stage1-worklist.json
sqlite3 \"\$DB\" \"SELECT COUNT(*) FROM event_log;\" \\
  | xargs -I{} echo \"stage1_event_log_rows={}\" | tee -a staged-import-metrics.txt
du -sh \"\$VAULT/.memoria\" | tee -a staged-import-metrics.txt"
  say "Record Shape-1 ask and Shape-2 explore latencies separately. More than 200 ms interactive triggers the substrate re-comparison early; record it either way."
  record "Stage 1 retrieval, attention/worklist, event-log, and database-size evidence"

  stage "Triage every Stage 1 attention item"
  step "Start a human wall clock and inspect every row in the one run-scoped worklist. For each item, you—not the wizard—select apply, reject, or defer and author the reason."
  show_command "memoria attention resolve --workspace \"\$VAULT\" <attention_path> --apply|--reject|--defer --reason \"<why>\""
  say "Record attention-item count, triage minutes, every selected disposition and reason, and whether the bounded batch fit within 60 minutes. The wizard will never select a disposition."
  record "Stage 1 PI triage of every attention item"

  stage "Prove disposition instrumentation"
  step "Query the authoritative event_log plane after triage. The count must be at least one, and you must inspect at least one disposition row whose item_id matches an attention path you just resolved."
  show_command "sqlite3 \"\$VAULT/.memoria/memoria.sqlite\" \\
  \"SELECT COUNT(*) FROM event_log WHERE event_type='disposition';\"   # must be >= 1"
  if confirm "Did the count exceed zero and did a disposition item_id match your resolved attention path?"; then
    LOOP13_STAGE2_ALLOWED=true
    record "Disposition instrumentation proof"
  else
    warn "Zero dispositions or no matching item is a hard result: record it, stop the protocol, and do not proceed to Stage 2."
    printf '  %sSTOP:%s Stage 2 is not licensed by this run.\n' "$RED" "$RESET"
    record "Disposition instrumentation failure"
  fi

  stage "Make the explicit staged-import stop decision"
  step "Read the dashboard and decide yourself whether triage volume, rebuild/query latency, a provider-policy prompt, or any other observation broke the session's flow. A manual rule does not fire automatically, and the wizard will not make this judgment."
  show_command "memoria dashboard --workspace \"\$VAULT\" --json"
  if confirm "Did you observe a staged-import stop condition?"; then
    LOOP13_STAGE2_ALLOWED=false
    warn "Record the observation before changing status. The observation IS the finding."
    say "Do not hand-write \$VAULT/.memoria/config/decision-rules.yaml; a one-entry file replaces the shipped registry."
    show_command "python -c \"from pathlib import Path; from memoria_vault.runtime.decision_rules import update_rule_status; \\
update_rule_status(Path('\$VAULT'), 'staged-import', 'fired')\""
    record "Staged-import stop observation and PI status update"
  else
    say "No rule action is needed. Record the no-stop decision; do not fire or retire a rule speculatively."
    record "Staged-import no-stop decision"
  fi

  stage "Conditionally repeat at 100 works"
  if [[ "$LOOP13_STAGE2_ALLOWED" == true ]] && confirm "Proceed with the 100-work stage after reviewing Stage 1 evidence?"; then
    step "Only now repeat the whole Stage 1 import, drain, retrieval, attention, PI triage, instrumentation, and stop-review block with stage2.bib. Take a fresh BEFORE watermark."
    step "Use the exact Stage 1 commands and frozen fixture arguments already reviewed, making only the plan-prescribed stage/file substitutions; the plan does not supply additional fixture fields or command arguments to invent."
    say "Stop at any stage where triage volume, rebuild/query latency, or provider policy breaks the session. Record the stop reason instead of pushing through."
    record "Stage 2 100-work repeat"
  else
    say "Stage 2 is blocked or declined. It runs only after Stage 1's instrumentation proof and no stop decision. Record the reason; do not push through."
    record "Stage 2 not run"
  fi

  stage "Rehearse the Phase 2 loop"
  show_command "memoria status --workspace \"\$VAULT\""
  step "Run one memoria project ask or memoria project gaps command against the framed live project. The plan does not prescribe its project identifiers or arguments; inspect the live project and CLI help rather than guessing."
  show_command "memoria list --workspace \"\$VAULT\" --type work"
  step "Confirm the admitted catalog is enumerated and record the status, project result, gaps or answer evidence, and catalog evidence."
  record "Phase 2 rehearsal"

  stage "Author and review the LOOP.13 acceptance record"
  step "Write docs/superpowers/specs/\$(date +%F)-staged-import-acceptance-run.md yourself. Include: vault freshness and never-test-vault attestation; licensed stage1.bib and stage2.bib provenance; seeded-error verdict; time_to_first_answer_s and the 1800-second bar; frozen fixture id, exact query/topic, declared depth, metric, and separate Shape-1 ask and Shape-2 explore latencies against 200 ms; each stage's import wall-clock and complete import-run.v1 row; enrichment drain result, provider-policy prompts, and per-stage retraction delta; attention items per 100 works, worklist evidence, triage minutes, every PI disposition and reason, and whether the batch fit within 60 minutes; event-log count, database-size evidence, disposition count greater than zero, and a matching item_id proof; every stop-rule observation, decision, status update, and stop reason; whether Stage 2 ran; and Phase 2 status, project, and catalog evidence."
  step "Review the resulting artifact for accuracy and secrets. A failed seeded-error verdict, zero disposition count, stop-rule observation, provider-policy prompt, or latency that broke session flow remains a recorded result and may block acceptance; never rewrite it as a pass."
  say "The PI may commit only after writing and reviewing the resulting artifact. The commit is optional."
  show_command "git add docs/superpowers/specs/\$(date +%F)-staged-import-acceptance-run.md
git commit -m \"docs(specs): staged 10->100 import acceptance run — recorded metrics

Co-Authored-By: Claude Fable 5 <noreply@anthropic.com>\""
  record "PI-authored staged-import-acceptance-run.md review and optional commit"
fi

if [[ "$SECTION" == "all" || "$SECTION" == "plugin" || "$SECTION" == "canvas" ]]; then
  say "Review the private temporary run log at $RUN_LOG."
  say "Transfer plugin and Canvas pass, fail, blocked, and skipped outcomes to the relevant PR description."
  say "The temporary log is working evidence, not the acceptance artifact."
fi
