#!/usr/bin/env python3
"""Materialize profile capability blocks from the tool registry."""

from __future__ import annotations

import argparse
import ast
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "vault-template"
PROFILES = SRC / ".memoria" / "profiles"
LANES = SRC / ".memoria" / "lane-overrides"
REGISTRY = SRC / ".memoria" / "tool-registry.yaml"
TASKS_MCP = SRC / ".memoria" / "mcp" / "tasks_mcp.py"
PROFILE_REFERENCE = ROOT / "docs/reference/profile-capabilities.md"

PLATFORM_KEYS = (
    "cli",
    "cron",
    "api_server",
    "telegram",
    "discord",
    "slack",
    "whatsapp",
    "whatsapp_cloud",
    "signal",
    "bluebubbles",
    "email",
    "homeassistant",
    "mattermost",
    "matrix",
    "dingtalk",
    "feishu",
    "wecom",
    "wecom_callback",
    "qqbot",
    "yuanbao",
    "teams",
    "google_chat",
)

TOOLSET_ORDER = (
    "skills",
    "todo",
    "kanban",
    "memory",
    "policy",
    "obsidian",
    "ingest",
    "cluster",
    "tasks",
    "patterns",
    "paper_search",
    "pyzotero",
    "qmd",
)

GENERATED = "# Generated by scripts/render_profile_configs.py; edit tool-registry.yaml.\n"
REFERENCE_START = "<!-- PROFILES:START -->"
REFERENCE_END = "<!-- PROFILES:END -->"
GENERATED_REFERENCE = (
    "<!-- Generated by scripts/render_profile_configs.py; edit profile sources instead. -->"
)
GENERATED_REFERENCE_PAGE = (
    "<!-- Generated by scripts/render_profile_configs.py; edit profile sources or generator text "
    "instead. -->"
)
PROFILE_ORDER = (
    "memoria-copi",
    "memoria-librarian",
    "memoria-writer",
    "memoria-peer-reviewer",
    "memoria-engineer",
)


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def _represent_list(dumper: Dumper, data: list):
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)


Dumper.add_representer(list, _represent_list)


def _registry() -> dict[str, Any]:
    return yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or {}


def load_registry() -> dict[str, Any]:
    return _registry()


def _tools_for(profile: str, registry: dict[str, Any]) -> list[str]:
    groups = registry["groups"]
    out: list[str] = []
    for entry in registry["profiles"][profile]["allow"]:
        for tool in groups.get(entry, [entry]):
            toolset = tool.split(".", 1)[0]
            if toolset not in out:
                out.append(toolset)
    return sorted(out, key=lambda item: TOOLSET_ORDER.index(item) if item in TOOLSET_ORDER else 99)


def toolsets_for(profile: str, registry: dict[str, Any]) -> list[str]:
    return _tools_for(profile, registry)


def _mcp_tools_for(profile: str, registry: dict[str, Any]) -> dict[str, list[str]]:
    groups = registry["groups"]
    out: dict[str, list[str]] = {}
    for entry in registry["profiles"][profile]["allow"]:
        for tool in groups.get(entry, [entry]):
            if "." not in tool:
                continue
            server, name = tool.split(".", 1)
            if name not in out.setdefault(server, []):
                out[server].append(name)
    return out


def mcp_tools_for(profile: str, registry: dict[str, Any]) -> dict[str, list[str]]:
    return _mcp_tools_for(profile, registry)


def render_profile(path: Path, registry: dict[str, Any]) -> str:
    profile = path.parent.name
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    toolsets = _tools_for(profile, registry)
    data["platform_toolsets"] = {platform: list(toolsets) for platform in PLATFORM_KEYS}

    expected_mcp = _mcp_tools_for(profile, registry)
    servers = data.get("mcp_servers") or {}
    for server, tools in expected_mcp.items():
        if server == "obsidian":
            continue
        if server not in servers:
            raise SystemExit(f"{profile}: registry grants missing MCP server {server}")
        servers[server].setdefault("tools", {})["include"] = tools

    rendered = yaml.dump(data, Dumper=Dumper, sort_keys=False, width=1000)
    rendered = rendered.replace(
        "  default: '{{MODEL_DEFAULT}}'\n",
        "  default: '{{MODEL_DEFAULT}}'\n  # {{MODEL_LOCAL_CONTEXT}}\n",
        1,
    )
    return GENERATED + rendered


def _load_yaml(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _profiles() -> list[str]:
    names = sorted(p.name for p in PROFILES.iterdir() if p.is_dir())
    return [name for name in PROFILE_ORDER if name in names] + [
        name for name in names if name not in PROFILE_ORDER
    ]


def _lane_override(profile: str) -> dict[str, Any]:
    path = LANES / f"{profile.removeprefix('memoria-')}.yaml"
    return _load_yaml(path) if path.is_file() else {}


def _lane_profile() -> dict[str, str]:
    tree = ast.parse(TASKS_MCP.read_text(encoding="utf-8"))
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(
            isinstance(target, ast.Name) and target.id == "LANE_PROFILE" for target in node.targets
        ):
            return ast.literal_eval(node.value)
    raise ValueError("tasks_mcp.py does not define LANE_PROFILE")


def _cell(value: object) -> str:
    if isinstance(value, list):
        value = ", ".join(f"`{item}`" for item in value) or "None"
    text = str(value).replace("\n", " ").replace("|", "\\|")
    return text or "None"


def _skills(profile: str) -> list[str]:
    root = PROFILES / profile / "skills"
    return sorted(p.name for p in root.iterdir() if p.is_dir()) if root.is_dir() else []


def render_reference_tables() -> str:
    registry = load_registry()
    lines = [
        REFERENCE_START,
        GENERATED_REFERENCE,
        "",
        "## The five profiles",
        "",
        "This block is generated from `vault-template/.memoria/profiles`, "
        "`vault-template/.memoria/lane-overrides`, "
        "`vault-template/.memoria/tool-registry.yaml`, and "
        "`vault-template/.memoria/mcp/tasks_mcp.py`.",
        "",
        "### Package metadata",
        "",
        "| Profile | Version | Hermes requirement | Invocation | Write scope |",
        "| --- | --- | --- | --- | --- |",
    ]
    for profile in _profiles():
        dist = _load_yaml(PROFILES / profile / "distribution.yaml")
        lane = _lane_override(profile)
        routing = lane.get("routing") or {}
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{profile}`",
                    _cell(dist.get("version")),
                    _cell(dist.get("hermes_requires")),
                    f"`{routing.get('invocation', 'interactive_only')}`",
                    _cell(routing.get("write_scope") or []),
                ]
            )
            + " |"
        )

    lines.extend(["", "### Lane routing", "", "| Task lane | Profile |", "| --- | --- |"])
    for lane, profile in sorted(_lane_profile().items()):
        lines.append(f"| `{lane}` | `{profile}` |")

    lines.extend(
        [
            "",
            "### MCP servers and toolsets",
            "",
            "| Profile | MCP servers | Platform toolsets |",
            "| --- | --- | --- |",
        ]
    )
    for profile in _profiles():
        config = _load_yaml(PROFILES / profile / "config.yaml")
        servers = sorted((config.get("mcp_servers") or {}).keys())
        lines.append(
            f"| `{profile}` | {_cell(servers)} | {_cell(toolsets_for(profile, registry))} |"
        )

    lines.extend(
        [
            "",
            "### Lane policy",
            "",
            "| Profile | Required controls | Explicitly denied write scopes |",
            "| --- | --- | --- |",
        ]
    )
    for profile in _profiles():
        policy = _lane_override(profile).get("policy") or {}
        lines.append(
            f"| `{profile}` | {_cell(policy.get('require') or [])} | "
            f"{_cell((policy.get('deny') or {}).get('write') or [])} |"
        )

    lines.extend(
        [
            "",
            "### Bundled skills",
            "",
            "| Profile | Count | Skills |",
            "| --- | ---: | --- |",
        ]
    )
    for profile in _profiles():
        skills = _skills(profile)
        lines.append(f"| `{profile}` | {len(skills)} | {_cell(skills)} |")

    lines.extend(["", REFERENCE_END, ""])
    return "\n".join(lines)


def render_reference_page() -> str:
    return (
        """---
title: Profile capabilities
parent: Agents and control
grand_parent: Reference
---

"""
        + GENERATED_REFERENCE_PAGE
        + f"""

# Profile capabilities

The five Memoria profiles ([ADR-48](../adr/48-copi-and-agent-consolidation.md)):
posture, board lanes, write scopes, MCP servers, and bundled skills. Every value
on this page is read from the shipped sources: profile packages under
`vault-template/.memoria/profiles`, lane ceilings under `vault-template/.memoria/lane-overrides`, and
the per-profile tool allowlist in `vault-template/.memoria/tool-registry.yaml`.

Alpha.11 routes only catalog, extract, link, map, and verify lanes. Writer/draft
and Engineer/code packages are present but deferred: their lane ceilings are
empty and the task router does not dispatch to them.

Regenerate with `python scripts/render_profile_configs.py reference --write`;
edit the profile, lane, and tool-registry sources, not this page.

{render_reference_tables().rstrip()}

## Related

- The write-gate decisions and lane-override shape: [Policy MCP](policy-mcp.md)
- The board the lanes pull from: [Kanban board reference](kanban-board.md)
- The CLI surface per profile: [Hermes CLI](hermes-cli.md)
- Where profiles live on disk: [On-disk layout](on-disk-layout.md)
"""
    ).strip() + "\n"


def check_configs(write: bool) -> list[Path]:
    registry = _registry()
    stale = []
    for profile in sorted(registry["profiles"]):
        path = PROFILES / profile / "config.yaml"
        rendered = render_profile(path, registry)
        current = path.read_text(encoding="utf-8")
        if current != rendered:
            stale.append(path)
            if write:
                path.write_text(rendered, encoding="utf-8")
    return stale


def check_reference(write: bool) -> bool:
    expected = render_reference_page()
    if write:
        PROFILE_REFERENCE.write_text(expected, encoding="utf-8")
        return False
    return PROFILE_REFERENCE.read_text(encoding="utf-8") != expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "target", nargs="?", choices=("config", "reference", "all"), default="config"
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    targets = ("config", "reference") if args.target == "all" else (args.target,)
    stale = check_configs(args.write) if "config" in targets else []
    reference_stale = check_reference(args.write) if "reference" in targets else False

    if args.check and stale:
        names = ", ".join(str(path.relative_to(ROOT)) for path in stale)
        raise SystemExit(
            f"profile configs are stale; run scripts/render_profile_configs.py --write: {names}"
        )
    if args.check and reference_stale:
        raise SystemExit(
            "docs/reference/profile-capabilities.md is stale; "
            "run scripts/render_profile_configs.py reference --write"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
