#!/usr/bin/env python3
"""Materialize profile capability blocks from the tool registry."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
PROFILES = SRC / ".memoria" / "profiles"
REGISTRY = SRC / ".memoria" / "tool-registry.yaml"

PLATFORM_KEYS = (
    "cli",
    "cron",
    "api_server",
    "telegram",
    "discord",
    "slack",
    "whatsapp",
    "whatsapp_cloud",
    "signal",
    "bluebubbles",
    "email",
    "homeassistant",
    "mattermost",
    "matrix",
    "dingtalk",
    "feishu",
    "wecom",
    "wecom_callback",
    "qqbot",
    "yuanbao",
    "teams",
    "google_chat",
)

TOOLSET_ORDER = (
    "skills",
    "todo",
    "kanban",
    "memory",
    "policy",
    "obsidian",
    "ingest",
    "cluster",
    "tasks",
    "patterns",
    "paper_search",
    "pyzotero",
    "qmd",
)

GENERATED = "# Generated by scripts/render_profile_configs.py; edit tool-registry.yaml.\n"


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def _represent_list(dumper: Dumper, data: list):
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)


Dumper.add_representer(list, _represent_list)


def _registry() -> dict[str, Any]:
    return yaml.safe_load(REGISTRY.read_text(encoding="utf-8")) or {}


def _tools_for(profile: str, registry: dict[str, Any]) -> list[str]:
    groups = registry["groups"]
    out: list[str] = []
    for entry in registry["profiles"][profile]["allow"]:
        for tool in groups.get(entry, [entry]):
            toolset = tool.split(".", 1)[0]
            if toolset not in out:
                out.append(toolset)
    return sorted(out, key=lambda item: TOOLSET_ORDER.index(item) if item in TOOLSET_ORDER else 99)


def _mcp_tools_for(profile: str, registry: dict[str, Any]) -> dict[str, list[str]]:
    groups = registry["groups"]
    out: dict[str, list[str]] = {}
    for entry in registry["profiles"][profile]["allow"]:
        for tool in groups.get(entry, [entry]):
            if "." not in tool:
                continue
            server, name = tool.split(".", 1)
            if name not in out.setdefault(server, []):
                out[server].append(name)
    return out


def render_profile(path: Path, registry: dict[str, Any]) -> str:
    profile = path.parent.name
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    toolsets = _tools_for(profile, registry)
    data["platform_toolsets"] = {platform: list(toolsets) for platform in PLATFORM_KEYS}

    expected_mcp = _mcp_tools_for(profile, registry)
    servers = data.get("mcp_servers") or {}
    for server, tools in expected_mcp.items():
        if server == "obsidian":
            continue
        if server not in servers:
            raise SystemExit(f"{profile}: registry grants missing MCP server {server}")
        servers[server].setdefault("tools", {})["include"] = tools

    rendered = yaml.dump(data, Dumper=Dumper, sort_keys=False, width=1000)
    rendered = rendered.replace(
        "  default: '{{MODEL_DEFAULT}}'\n",
        "  default: '{{MODEL_DEFAULT}}'\n  # {{MODEL_LOCAL_CONTEXT}}\n",
        1,
    )
    return GENERATED + rendered


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()

    registry = _registry()
    stale = []
    for profile in sorted(registry["profiles"]):
        path = PROFILES / profile / "config.yaml"
        rendered = render_profile(path, registry)
        current = path.read_text(encoding="utf-8")
        if current != rendered:
            stale.append(path)
            if args.write:
                path.write_text(rendered, encoding="utf-8")

    if args.check and stale:
        names = ", ".join(str(path.relative_to(ROOT)) for path in stale)
        raise SystemExit(
            f"profile configs are stale; run scripts/render_profile_configs.py --write: {names}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
