title: Memoria
description: Personal knowledge management documentation
baseurl: ""
url: ""

theme: jekyll-hacker@v0.2.0 # Use remote_theme if using an external GitHub community theme

markdown: kramdown


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
