#!/usr/bin/env python3
"""Validate agent guidance and regenerate its derived reference pages."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
AGENTS = ROOT / ".agents"
GUIDANCE_DIRS = (".agents", ".claude", ".codex", ".kilo")
IMPACT_SOURCE = AGENTS / "system/change-impact.yaml"
IMPACT_DOC = AGENTS / "system/change-impact-map.md"
RULESET_CONTRACT = ROOT / ".github/ruleset-contract.yaml"
GENERATED = "<!-- Generated by scripts/checks/agents_doctor.py; edit the source YAML instead. -->"
REQUIRED_FILES = (
    "README.md",
    "playbooks/code-review.md",
    "playbooks/docs-review.md",
    "playbooks/security-review.md",
    "playbooks/verify-change.md",
    "system/change-impact.yaml",
    "system/source-of-truth-map.md",
    "system/test-selection.md",
)


def _render_impact(data: dict) -> str:
    lines = [
        GENERATED,
        "# Change-impact map",
        "",
        "This map answers: “When I change this, what else must I inspect?” It is a",
        "review frontier, not permission to edit every listed file.",
        "",
        "| Change area | Changed paths | Inspect together | Primary checks |",
        "|---|---|---|---|",
    ]
    for row in data["areas"]:
        paths = "<br>".join(f"`{item}`" for item in row["paths"])
        inspect = "<br>".join(row["inspect"])
        checks = "<br>".join(f"`{item}`" for item in row["checks"])
        lines.append(f"| {row['area']} | {paths} | {inspect} | {checks} |")
    lines.extend(
        [
            "",
            "## How to use the map",
            "",
            "1. Start from the changed row.",
            "2. Inspect each named contract for drift.",
            "3. Edit only consumers that genuinely need to change.",
            "4. Run focused checks from the row.",
            "5. Use [test selection](test-selection.md) to decide whether the full gate is required.",
            "",
        ]
    )
    return "\n".join(lines)


def _local_link_errors() -> list[str]:
    errors = []
    link_re = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
    roots = [ROOT / name for name in GUIDANCE_DIRS if (ROOT / name).is_dir()]
    for path in sorted(p for root in roots for p in root.rglob("*.md")):
        for target in link_re.findall(path.read_text(encoding="utf-8")):
            target = target.split("#", 1)[0]
            if not target or "://" in target or target.startswith("#"):
                continue
            if not (path.parent / target).resolve().exists():
                errors.append(f"{path.relative_to(ROOT)}: broken link {target}")
    return errors


def _skill_errors() -> list[str]:
    errors = []
    skill_roots = [
        ROOT / ".agents" / "skills",
        ROOT / ".claude" / "skills",
        ROOT / ".codex" / "skills",
        ROOT / ".kilo" / "skills",
    ]
    for path in sorted(p for root in skill_roots if root.is_dir() for p in root.glob("*/SKILL.md")):
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            errors.append(f"{path.relative_to(ROOT)}: missing YAML frontmatter")
            continue
        _, frontmatter, _ = text.split("---", 2)
        data = yaml.safe_load(frontmatter) or {}
        for key in ("name", "description"):
            if not data.get(key):
                errors.append(f"{path.relative_to(ROOT)}: missing {key}")
    return errors


def _required_ci_checks_from_agents(text: str) -> list[str]:
    lines = iter(text.splitlines())
    for line in lines:
        if line == "## Required CI checks":
            break
    else:
        return []

    checks = []
    in_table = False
    for line in lines:
        if line == "| Check | Validates |":
            in_table = True
            continue
        if in_table and line == "|---|---|":
            continue
        if in_table and (found := re.match(r"^\| `([^`]+)` \|", line)):
            checks.append(found.group(1))
            continue
        if in_table:
            break
    return checks


def _required_ci_errors() -> list[str]:
    expected = (yaml.safe_load(RULESET_CONTRACT.read_text(encoding="utf-8")) or {}).get(
        "required_checks"
    )
    actual = _required_ci_checks_from_agents((ROOT / "AGENTS.md").read_text(encoding="utf-8"))
    if actual != expected:
        return [
            "AGENTS.md Required CI checks drift from .github/ruleset-contract.yaml: "
            f"{actual} != {expected}"
        ]
    return []


def _impact_errors(data: dict) -> list[str]:
    errors = []
    if data.get("version") != 1:
        errors.append("change-impact.yaml: must contain version: 1")
    areas = data.get("areas")
    if not isinstance(areas, list) or not areas:
        errors.append("change-impact.yaml: must contain a non-empty areas list")
        return errors

    reference_re = re.compile(r"(?:tests|scripts|src)/[A-Za-z0-9_./*-]+")
    seen_areas: set[str] = set()
    for index, row in enumerate(areas, start=1):
        if not isinstance(row, dict):
            errors.append(f"change-impact.yaml: area #{index} must be a mapping")
            continue
        area = row.get("area")
        if not isinstance(area, str) or not area.strip():
            errors.append(f"change-impact.yaml: area #{index} missing area")
            area = f"area #{index}"
        elif area in seen_areas:
            errors.append(f"change-impact.yaml: duplicate area {area}")
        else:
            seen_areas.add(area)

        for key in ("paths", "inspect", "checks"):
            values = row.get(key)
            if not isinstance(values, list) or not values:
                errors.append(f"change-impact.yaml: {area} {key} must be a non-empty list")
                continue
            seen_values: set[str] = set()
            for value in values:
                if not isinstance(value, str) or not value.strip():
                    errors.append(f"change-impact.yaml: {area} {key} contains a blank item")
                    continue
                if value in seen_values:
                    errors.append(f"change-impact.yaml: {area} {key} contains duplicate {value}")
                seen_values.add(value)

        paths = row.get("paths") if isinstance(row.get("paths"), list) else []
        checks = row.get("checks") if isinstance(row.get("checks"), list) else []
        for pattern in paths:
            if not isinstance(pattern, str):
                continue
            prefix = re.split(r"[*?[]", pattern, maxsplit=1)[0].rstrip("/")
            candidate = ROOT / prefix
            if prefix and not candidate.exists():
                errors.append(f"change-impact.yaml: missing path prefix {prefix}")
        for command in checks:
            if not isinstance(command, str):
                continue
            for reference in reference_re.findall(command):
                if "*" not in reference and not (ROOT / reference).exists():
                    errors.append(f"change-impact.yaml: command references missing {reference}")
    return errors


def check(write: bool = False) -> list[str]:
    errors = _local_link_errors() + _skill_errors()
    for relative in REQUIRED_FILES:
        if not (AGENTS / relative).is_file():
            errors.append(f".agents/{relative}: required guidance file is missing")
    try:
        errors.extend(_required_ci_errors())
        data = yaml.safe_load(IMPACT_SOURCE.read_text(encoding="utf-8")) or {}
        impact_errors = _impact_errors(data)
        errors.extend(impact_errors)
        rendered = {} if impact_errors else {IMPACT_DOC: _render_impact(data)}
    except (OSError, ValueError, yaml.YAMLError) as exc:
        return [*errors, str(exc)]
    for path, expected in rendered.items():
        if write:
            path.write_text(expected, encoding="utf-8")
        elif not path.is_file() or path.read_text(encoding="utf-8") != expected:
            errors.append(
                f"{path.relative_to(ROOT)}: stale; run scripts/checks/agents_doctor.py --write"
            )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="regenerate derived references")
    args = parser.parse_args()
    errors = check(args.write)
    if errors:
        print("\n".join(f"ERROR: {error}" for error in errors), file=sys.stderr)
        return 1
    print("agents-doctor: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
